### ISSUE TITLE
Kdump not generating proper Xen Crashdump Analyzer file on XCP-ng 8.2

### ISSUE THREAD

**Issue by user-36428** [xcp-ng/xcp#476] opened 2021-01-16 19:57 UTC
While trying to analyze a crash dump, I noticed it was not being created properly by kdump

# head xen-crashdump-analyser.log 
INFO  Logging level is DEBUG
INFO  Command line: /usr/lib64/xen/bin/xen-crashdump-analyser --outdir /var/crash/20210111-114333-EST --xen-symtab /boot/xen-4.13.1-9.8.2.xcpng8.map --dom0-symtab /var/lib/kdump/System.map-4.19.0+1 -v --dump-structures
INFO  Xen Crashdump Analyser version 2.5.5
DEBUG Opened log file 'xen-crashdump-analyser.log'
INFO  Output directory: /var/crash/20210111-114333-EST/
ERROR realpath failed for Xen symbol table path '/boot/xen-4.13.1-9.8.2.xcpng8.map': No such file or directory
...

Notice anything missing - hint: look at the symbol table file name for --xen-symtab 
Oops, looks like 8.2 is missing....

/usr/sbin/kdump not getting correct version info from /proc/cmdline

Something missed when migrating from /var/lib/ to /boot on --xen-symtab line from 8.1 -> 8.2

**Comment by stormi** [comment] 2021-01-19 15:48
Thanks for your report. I'll need to dig to be sure I understand the cause of the issue in detail.

**Comment by rushikeshjadhav** [comment] 2021-01-21 17:56
@user-36428 temporarily you can fix it with `# ln -sf /boot/xen-4.13.1-9.8.2.xcpng8.2.map  /boot/xen-4.13.1-9.8.2.xcpng8.map`. The issue is also applicable on XCP-ng 8.1.

**Comment by user-36428** [comment] 2021-01-21 18:52
I never had this problem after generating crash logs under XCP-ng 8.1. Notice the first several lines from one of my recent XCP-ng 8.1 crash logs showing the correct format for the symbol table file name:

# more xen-crashdump-analyser.log 
INFO  Logging level is DEBUG
INFO  Command line: /usr/lib64/xen/bin/xen-crashdump-analyser --outdir /var/crash/20200
720-084115-EDT **--xen-symtab /var/lib/kdump/xen-4.13.0-8.4.xcpng8.1.map** --dom0-symtab /v
ar/lib/kdump/System.map-4.19.0+1 -v --dump-structures
INFO  Xen Crashdump Analyser version 2.5.4
DEBUG Opened log file 'xen-crashdump-analyser.log'
INFO  Output directory: /var/crash/20200720-084115-EDT/
INFO  Xen symbol table: /var/lib/kdump/xen-4.13.0-8.4.xcpng8.1.map
DEBUG   text section limits: 0xffff82d080200000->0xffff82d0803711ba
DEBUG   init section limits: 0xffff82d0803c5000->0xffff82d0804092ad
DEBUG Got Xen virtual address information. Will validate Xen pointers
INFO  Dom0 symbol table: /var/lib/kdump/System.map-4.19.0+1
INFO  CPU vendor is Intel

Therefore, the temporary soft link fix does not appear to be necessary for XCP-ng 8.1 just 8.2. I have applied this temporary workaround for 8.2 in order to obtain a crash log file. Luckily, I have not had the opportunity to test it yet.

At some point during the migration from 8.1 -> 8.2, kdump changed it's location for symbol table lookup from /var/lib/kdump to /boot. I suspect the logic in kdump deriving the version number did not get migrated during that time. In any event, I appreciate you looking into this problem and for the temporary fix.

**Comment by user-36428** [comment] 2021-01-22 16:29
@olivierlambert Any particular reason for removing the bold highlight to the --xen-symtab filename? I made that bold to make it standout and easier to spot for anyone viewing this post. Now it just looks odd with the asterisks and someone may think they should be there.... Just wondering is all.

**Comment by olivierlambert** [comment] 2021-01-22 16:40
Because not using the markdown syntax made an ugly display. I didn't spotted the bold on the line. Let me edit the post to make it more clear.

**Comment by user-36428** [comment] 2021-01-22 19:04
I could have swore the preview showed the bold when I was doing it. Anyway, thanks for updating the post.

**Comment by rushikeshjadhav** [comment] 2021-01-24 05:12
@user-36428 May be its an issue with upgrade and not with clean installs. I think my system was upgraded from 8 to 8.1 where I faced this issue. Did you do clean 8.1 install or had upgraded?

**Comment by user-36428** [comment] 2021-01-24 14:03
Clean install for both 8.1 and 8.2. I never upgrade, always do clean installs - not worth the side-effects.

**Comment by stormi** [comment] 2021-01-25 16:06
I'm having a look. Note: to easily reproduce, one can provoke a kernel crash with `echo c > /proc/sysrq-trigger`

**Comment by stormi** [comment] 2021-01-25 17:18
The issue comes from `/sys/hypervisor/version/extra` which ends in `xcpng8` instead of `xcpng8.2`, so the generated map filename is wrong.

**Comment by olivierlambert** [comment] 2021-01-25 17:29
Good catch!

**Comment by stormi** [comment] 2021-01-25 17:57
`/sys/hypervisor/version/extra` can't hold more than 16 characters, so whenever the release tag of our RPM is too long, it gets truncated, hence causing the mismatch with the actual file names where it's not truncated.

**Comment by stormi** [comment] 2021-01-26 16:07
I have published an update candidate that fixes this issue: https://xcp-ng.org/forum/post/35888

**Comment by user-36428** [comment] 2021-01-26 20:09
Thanks @stormi appreciate you getting this fixed.

**Comment by stormi** [comment] 2021-01-26 22:07
Thanks for reporting it in the first place :)

**Comment by stormi** [comment] 2021-02-26 14:47
Fixed with the latest Xen update for 8.1 and 8.2.

**Closed by stormi** 2021-02-26 14:47 UTC
