### ISSUE TITLE
Windows XP VMs won't boot on xcp-ng 8.0

### ISSUE THREAD

**Issue by svensen** [xcp-ng/xcp#247] opened 2019-07-26 11:51 UTC
On xcp-ng 8.0, Windows XP with either Citrix or free PV storage drivers crashes on boot.
DomU shuts down without blue screen or any other visible error.
/var/log/xensource.log is quite verbose, I dont't now exactly how to identify relevant lines.

**Comment by olivierlambert** [comment] 2019-07-26 12:24
Hi,

I'm not sure if there is anyone willing/able to diagnose Windows XP issues, but still, I'm keeping this open in case someone from the community knows anything about this.

Also, please provide your logs.

**Comment by olivierlambert** [comment] 2019-07-26 12:25
@svensen are you able to test also with Citrix Hypervisor 8.0, so we know it's "upstream" or something in XCP-ng?

**Comment by stormi** [comment] 2019-07-26 13:11
For reference (the original poster already knows about it), there's also a thread here https://xcp-ng.org/forum/topic/1361/windows-xp-guest-wont-boot-after-upgrade-von-xenserver-6-5-to-xcp-ng-7-6 where for some it failed on 7.6 already, and for others it worked. I don't know if the root cause is related.

**Comment by olivier-monaco** [comment] 2019-08-20 10:25
Same problem after an upgrade from XCP-ng 7.4 to 8.0. Windows XP does not boot in "normal" mode but works in "rescue" mode. I'm investigating...

**Comment by olivierlambert** [comment] 2019-08-20 10:29
That's likely due to Citrix tools/PV drivers unsupported on Windows < Vista (see https://xcp-ng.org/forum/post/15782)

**Comment by olivier-monaco** [comment] 2019-08-20 13:39
Yes it seems to come from the PV driver. I don't think it is not supported, more it crashes during Windows boot. As stated in forum, removing PV driver resolve the problem but performances are bad. Trying to install an older version of PV driver do the same. I tried to debug Windows XP boot but MS did not include much stuff... I just can say Windows crash when drivers are initialized.

In xensource.log, there's:
```
Aug 20 15:20:19 callisto xenopsd-xc: [debug|callisto|7 ||xenops] Got QMP event, domain-29: XEN_PLATFORM_PV_DRIVER_INFO
Aug 20 15:20:19 callisto xenopsd-xc: [debug|callisto|7 ||xenops] Got QMP event, domain-29: XEN_PLATFORM_PV_DRIVER_INFO
Aug 20 15:20:19 callisto xenopsd-xc: [debug|callisto|7 ||xenops] Got QMP event, domain-29: DEVICE_DELETED
Aug 20 15:20:19 callisto xenopsd-xc: [debug|callisto|7 ||xenops] QMP command for domid 29: {"execute":"query-migratable","id":"qmp-000130-29"}
Aug 20 15:20:19 callisto xenopsd-xc: [debug|callisto|7 ||xenops] received QMP response qmp-000130-29 (File "xc/device_common.ml", line 411, characters 49-56)
Aug 20 15:20:19 callisto xenopsd-xc: [debug|callisto|7 ||xenops] query-migratable precheck passed (domid=29)
Aug 20 15:20:19 callisto xenopsd-xc: [debug|callisto|7 ||xenops] xenstore-rm /local/domain/29/data/cant_suspend_reason
Aug 20 15:20:20 callisto xenopsd-xc: [debug|callisto|7 ||xenops] Got QMP event, domain-29: XEN_PLATFORM_PV_DRIVER_INFO
```
An then the VM crash.

When a Windows 10 VM boot we have:
```
Aug 20 15:32:46 callisto xenopsd-xc: [debug|callisto|7 ||xenops] Got QMP event, domain-31: XEN_PLATFORM_PV_DRIVER_INFO
Aug 20 15:32:46 callisto xenopsd-xc: [debug|callisto|7 ||xenops] Got QMP event, domain-31: DEVICE_DELETED
Aug 20 15:32:46 callisto xenopsd-xc: [debug|callisto|7 ||xenops] QMP command for domid 31: {"execute":"query-migratable","id":"qmp-000143-31"}
Aug 20 15:32:46 callisto xenopsd-xc: [debug|callisto|7 ||xenops] received QMP response qmp-000143-31 (File "xc/device_common.ml", line 411, characters 49-56)
Aug 20 15:32:46 callisto xenopsd-xc: [debug|callisto|7 ||xenops] query-migratable precheck passed (domid=31)
Aug 20 15:32:46 callisto xenopsd-xc: [debug|callisto|7 ||xenops] xenstore-rm /local/domain/31/data/cant_suspend_reason
```

I think Windows XP on XCP-ng 8 is a dead end.

**Comment by olivierlambert** [comment] 2019-08-20 14:06
Yeah it's possible that PV drivers cause crashed on Windows XP using a more recent version of Xen (in XCP-ng 8.0).

**Comment by olivierlambert** [comment] 2019-08-20 15:39
See https://xcp-ng.org/forum/post/15854

**Comment by olivierlambert** [comment] 2019-08-20 17:13
Closing as we now know what cause XP crashes on 8.0 (ie Xen 4.11 without ugly hacks in Citrix previous patch queue)

Workarounds are:

1. XP without PV drivers, until your XP are decommissioned 
2. Using XCP-ng 7.6, until your XP are decommissioned 

In other words, get rid of those XP as soon as you can. If you want them anyway, you can fetch those ugly hacks from 7.6 and import them to 8.0. Here is the list of those patches:

```
# Un-upstreamable hacks to make older windows VMs continue to function on newer Xen
xen-legacy-win-driver-version.patch
xen-legacy-win-xenmapspace-quirks.patch
xen-legacy-32bit_shinfo.patch
xen-legacy-process-dying.patch
xen-legacy-viridian-hypercalls.patch
xen-legacy-hvm-console.patch
```

**Closed by olivierlambert** 2019-08-20 17:13 UTC
Labels: windows guest tools and drivers

**Comment by Island-Breeze** [comment] 2021-07-28 02:23
Sorry I know this is closed.  But thought I would like to add.
I have a legacy Windows 2000 server that we P2V years ago.
this works in Xenserver 7.1, but i had to use Acronis ISO disk to boot the VM.
i just add it as an ISO in the VM.
When i migrated to XCP-NG this VM still works.
![Windows2000VMRunningInXcp](https://user-images.githubusercontent.com/88068245/127253474-c0867e08-ac7a-455f-8642-0896b4bcdb85.png)

**Comment by olivierlambert** [comment] 2021-07-28 06:59
They all can work but without PV drivers (because hypercall with 2000/XP will likely crash the VM)
