### ISSUE TITLE
Software raid install fails 

### ISSUE THREAD

**Issue by oallart** [xcp-ng/xcp#155] opened 2019-03-13 01:25 UTC
Looks similar to https://github.com/xcp-ng/xcp/issues/75
Could be related to https://github.com/xcp-ng/xcp/issues/107 (need a proper wipe)

xcp-ng 7.5.0-2 - Previously used disks with md's, but clean wiped (mdadm, wipefs, sgdisk -Z etc.)

Log below:

```
INFO     [2019-02-12 04:24:42] TASK: Evaluating <function inspectTargetDisk at 0x21b0e60>['/dev/md127', None, [], 'if-utility', True, True]
INFO     [2019-02-12 04:24:42] Installer booted in legacy mode
INFO     [2019-02-12 04:24:43] ran ['blkid', '-s', 'PTTYPE', '-o', 'value', '/dev/md127']; rc 2
INFO     [2019-02-12 04:24:43] ran ['blockdev', '--getss', '/dev/md127']; rc 0
STANDARD OUT:
512

INFO     [2019-02-12 04:24:43] ran ['blockdev', '--getsize64', '/dev/md127']; rc 0
STANDARD OUT:
0

INFO     [2019-02-12 04:24:43] ran ['sgdisk', '--print', '/dev/md127']; rc 0
STANDARD OUT:

***************************************************************
Found invalid GPT and valid MBR; converting MBR to GPT format.
***************************************************************

Disk /dev/md127: 0 sectors, 0 bytes
Logical sector size: 512 bytes
Disk identifier (GUID): B42B46A7-97F2-405D-A26E-2AE964CF1AE4
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 18446744073709551582
Partitions will be aligned on 2048-sector boundaries
Total free space is 0 sectors (0 bytes)

Number  Start (sector)    End (sector)  Size       Code  Name

STANDARD ERROR:
Problem reading disk in BasicMBRData::ReadMBRData()!
Warning! Read error 22; strange behavior now likely!
Warning! Read error 22; strange behavior now likely!

INFO     [2019-02-12 04:24:43] Warning: GPTPartitionTool found DOS partition table on device /dev/md127
INFO     [2019-02-12 04:24:44] ran ['/sbin/udevadm', 'settle', '--timeout=30']; rc 0
INFO     [2019-02-12 04:24:44] Fresh install, target_boot_mode: legacy
INFO     [2019-02-12 04:24:44] DISPATCH: Updated state: target-boot-mode -> legacy; backup-partnum -> 2; swap-partnum -> 6; boot-partnum -> 4; storage-partnum -> 3; primary-partnum -> 1; logs-partnum -> 5
INFO     [2019-02-12 04:24:44] TASK: Evaluating <function selectPartitionTableType at 0x21b0ed8>['/dev/md127', 'fresh', 1, True]
INFO     [2019-02-12 04:24:44] ran ['blkid', '-s', 'PTTYPE', '-o', 'value', '/dev/md127']; rc 2
INFO     [2019-02-12 04:24:44] ran ['blockdev', '--getss', '/dev/md127']; rc 0
STANDARD OUT:
512

INFO     [2019-02-12 04:24:44] ran ['blockdev', '--getsize64', '/dev/md127']; rc 0
STANDARD OUT:
0

INFO     [2019-02-12 04:24:44] ran ['sgdisk', '--print', '/dev/md127']; rc 0
STANDARD OUT:

***************************************************************
Found invalid GPT and valid MBR; converting MBR to GPT format.
***************************************************************

Disk /dev/md127: 0 sectors, 0 bytes
Logical sector size: 512 bytes
Disk identifier (GUID): 8E12EBB1-C098-4F44-8951-908E2A1B7F11
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 18446744073709551582
Partitions will be aligned on 2048-sector boundaries
Total free space is 0 sectors (0 bytes)

Number  Start (sector)    End (sector)  Size       Code  Name

STANDARD ERROR:
Problem reading disk in BasicMBRData::ReadMBRData()!
Warning! Read error 22; strange behavior now likely!
Warning! Read error 22; strange behavior now likely!

INFO     [2019-02-12 04:24:44] Warning: GPTPartitionTool found DOS partition table on device /dev/md127
INFO     [2019-02-12 04:24:45] ran ['/sbin/udevadm', 'settle', '--timeout=30']; rc 0
INFO     [2019-02-12 04:24:45] DISPATCH: Updated state: partition-table-type -> GPT
INFO     [2019-02-12 04:24:45] TASK: Evaluating <function verifyRepos at 0x21b2230>[[{'media': 'url', 'address': 'http://mirror.benon.com/pub/xcp-ng/7.5.0/os/'}], <module 'tui' from '/opt/xensource/installer/tui/__init__.py'>]
INFO     [2019-02-12 04:24:45] Initializing URLRepositoryAccessor with base address http://mirror.benon.com/pub/xcp-ng/7.5.0/os/
INFO     [2019-02-12 04:24:47] TASK: Evaluating <function removeBlockingVGs at 0x21b0f50>[['/dev/md127']]
INFO     [2019-02-12 04:24:47] ran ['/sbin/lvm', 'vgs', '--noheadings', '--nosuffix', '--units', 'b', '--separator', '#', '--options', 'vg_name']; rc 0
INFO     [2019-02-12 04:24:47] ran ['/sbin/lvm', 'lvs', '--noheadings', '--nosuffix', '--units', 'b', '--separator', '#', '--options', 'lv_name,vg_name']; rc 0
INFO     [2019-02-12 04:24:47] ran ['/sbin/lvm', 'lvs', '--noheadings', '--nosuffix', '--units', 'b', '--separator', '#', '--segments', '--options', 'seg_pe_ranges']; rc 0
INFO     [2019-02-12 04:24:47] ran ['/sbin/lvm', 'pvs', '--noheadings', '--nosuffix', '--units', 'b', '--separator', '#', '--options', 'pv_name,vg_name,pe_start,pv_size,pv_free,pv_pe_count,dev_size']; rc 0
INFO     [2019-02-12 04:24:47] TASK: Evaluating <function writeDom0DiskPartitions at 0x21ad050>['/dev/md127', 'legacy', 4, 1, 2, 5, 6, 3, True, 'GPT', True, False]
INFO     [2019-02-12 04:24:47] INSTALL FAILED.
INFO     [2019-02-12 04:24:47] A fatal exception occurred:
INFO     [2019-02-12 04:24:47] Traceback (most recent call last):
  File "/opt/xensource/installer/install.py", line 267, in go
    backend.performInstallation(results, ui, interactive)
  File "/opt/xensource/installer/backend.py", line 351, in performInstallation
    executeSequence(prep_seq, "Preparing for installation...", answers, ui_package, False)
  File "/opt/xensource/installer/backend.py", line 259, in executeSequence
    updated_state = item.execute(answers, progressCallback)
  File "/opt/xensource/installer/backend.py", line 85, in execute
    rv = apply(self.fn, args)
  File "/opt/xensource/installer/backend.py", line 577, in writeDom0DiskPartitions
    raise RuntimeError, "The disk %s is smaller than %dGB." % (disk, constants.min_primary_disk_size_old)
RuntimeError: The disk /dev/md127 is smaller than 12GB.

```
After restarting the system and tryingre-installing, problem was gone.

It's not easy to trigger, but when it happens, for some reason a mbr is detected and conversion to GPT is attempted (even though there is no MBR, but I suspect this might be a default somewhere). Also, this:

```
STANDARD ERROR:
Problem reading disk in BasicMBRData::ReadMBRData()!
Warning! Read error 22; strange behavior now likely!
Warning! Read error 22; strange behavior now likely!
```

I looked into this as well, without much success. It points (again) to an erroneous MBR detection. MBR and partition signatures were wiped before. I even tried to create a GPT on purpose but still ran into this error.
Hope it helps.

**Comment by stormi** [comment] 2019-03-14 11:45
Thanks for the report. I don't know how we will be able to debug this without a way to reproduce, but at least we've got the logs. Have you kept the full installation log, just in case?

**Comment by oallart** [comment] 2019-03-15 00:37
Unfortunately no, but I will next time I run into this.

**Comment by stormi** [comment] 2019-11-22 17:08
Closing since we can't reproduce on that system and I think it's indeed related to #107

**Closed by stormi** 2019-11-22 17:08 UTC
