### ISSUE TITLE
Unable to boot installer with AMD Ryzen APUs

### ISSUE THREAD

**Issue by nagilum99** [xcp-ng/xcp#206] opened 2019-06-24 09:57 UTC
As from the Forum:
There seems to be a kernel bug, preventing several kernels from booting on AMD Ryzen APUs, unless maxmem:2048M is set (maybe a higher value works, but this was a recommendation from the OPSI forums and it worked on their linux boot image and for XCP-ng 8.0.0 Beta + CH 8).
Tested hardware:
AMD Ryzen R5 2400G
AMD Ryzen R5 2200G
AMD Athlon 240G
Asus Prime A320M A BIOS 4801
Gigabyte GA-A320M-S2H V2 BIOS F30

It probably makes sense to upstream at least the problem itself. Also some kernel maintainers should be aware of the problem?

I could test different (newer) images, if you want me to. Didn't test on Epyic, but I assume it's related to APU and shared memory for GPU (which is usually located above 4G and thus could collide, if not proper handled).

XCP-ng 7.6 works! (It's known to work with older kernels!)

More references:
https://forum.opsi.org/viewtopic.php?f=8&t=10611 (Et al.)

Solution: Either edit grub.cfg/grub64.cfg on your install media or press "e" during Grub menu, change 8192 value to 2048 and press F10 to boot.

**Comment by MasterSteelblade** [comment] 2019-06-28 19:56
Able to confirm this as an issue, but affecting non-APU Ryzen as well - havn't been able to try with maxmem settings, but all USB devices hang after some ELF messages. Using a Ryzen 1700 on a B450 platform. XCP-ng 7.6 works.

**Comment by nagilum99** [comment] 2019-06-28 21:15
It takes like... 10 seconds to apply the documented workaround.

**Comment by varnav** [comment] 2019-07-26 16:26
AMD Ryzen 7 1700X server. I'm running 7.6, and was trying to upgrade to 8.0
ISO gives some initial boot messages, but eventually gets stuck with black screen.
Those problems did not occur with 7.6 ISO.

I don't want to play with workarounds, better wait this to be fixed.

**Comment by stormi** [comment] 2019-07-26 20:06
> I don't want to play with workarounds, better wait this to be fixed.

We don't know how to fix it yet and the fix probably belongs into the kernel. Lowering the RAM values for everyone would just make other kinds of hardware fail (this is why it has been set to 8Gb by Citrix in the first place, from what I know).

As @nagilum99 said: "press e during grub menu, change 8192 value to 2048 and press F10 to boot.". If you need to do that to many hosts, you can extract the ISO, change grub.cfg and rebuild the ISO. See https://github.com/xcp-ng/xcp/wiki/Modifying-the-installer

**Comment by pblakez** [comment] 2019-09-03 01:47
confirm issue on
Gigabyte B450 AORUS M (rev. 1.0) Bios 41a
AMD Ryzen R5 3400G

**Comment by cflaviu** [comment] 2019-11-10 21:06
same issue on
Gigabyte AB350 Pro4 - BIOS 5.80
AMD Ryzen 7 1700
16 GB RAM

**Comment by cflaviu** [comment] 2019-11-10 22:01
I rebuit iso image by changing dom0_mem=max:8192M to dom0_mem=max:2048M in grub.cfg and grub-usb.cfg but no luck.

In safe mode log I noticed:

> ACPI sleep modes: S3
> VPMU: disabled
> xenoprof: Initialization failed. AMD processor family 23 is not supported
> ......
> Hardware Dem0 halted: halting machine

In BIOS, CPU virtualization (SVM Mode) is Enabled and ACPI S3 (Suspend to RAM) is Disabled. Enabling ACPI S3 has no effect, same halting.

**Comment by olivierlambert** [comment] 2019-11-11 08:46
Without rebuilding, just modifying the menu with the value doesn't work?

**Comment by cflaviu** [comment] 2019-11-14 10:22
Sorry for the late reply. I couldn't trigger the edit of grub menu pressing e key and I switched to XCP-ng 7.6 which works fine.

**Comment by nagilum99** [comment] 2019-11-14 14:08
If you couldn't trigger it, as described, something else is wrong.

**Comment by DavorSaric** [comment] 2019-11-14 16:54
Hello, I am trying version 8 on Hetzner AX41-NVMe with AMD Ryzen 5 3600 and no luck. Following solution doesn't work, server still reboots during CD boot. Currenty installing v7.6. and boot is stuck at:
Xen is relinquishing VGA console and then server restarts. I will try now usb instead of UEFI boot. I hope I didn't waist 100EUR down the drain.

**Comment by nagilum99** [comment] 2019-11-14 17:15
That's a different problem then. The solution above works for the symptom described.
If it reboots during boot, then it's something else. As usual debug-recommendations:
Try to disable all power saving settings in the BIOS.
Dunno what USB boot should be, but you should try to boot either via UEFI and BIOS mode. Sometimes one thing is buggy.

Noone's gonna refund you anything. You're using OSS for free - but maybe they refund you 100 € if you pay for a supported license before.
People may try to help you debugging the problem but it's also on you to dig deeper and give some helpful infos about the problem. That means: More details - as many as you can provide.

I'm too lazy to google for the 'reboot problem' (and that would be your part anyways),
but I have in mind, that someone already had that problem.

**Comment by DavorSaric** [comment] 2019-11-14 17:18
I cannot paste you the output as I am in KVM. USB is BIOS(legacy) mode.

**Comment by rjt** [comment] 2019-11-14 17:19
Wouldnt a serial port debug session help figure this out?

Have firmware updates been applied?

Intel chips take such a performance hit after applying all MeltDown and
latest spectre patches and then disabling HyperThreading.   AMD does not
take nearly the performance hit and has so many more lanes for NVMe.

**Comment by rjt** [comment] 2019-11-14 17:53
Davor,

that is why serial ports can be used for debugging at times.  Another
option would be to take a pic with your cell phone.  AdobeScan, Google, or
the  CopyFish web browser extension can do OCR to convert the bulk of it to
text.  Search and replace badly converted characters with notepad.

 I do not know if the list accepts pictures, but try cropping down the size
and saving ad PNG to make it most likely to get thru the filters.

**Comment by DavorSaric** [comment] 2019-11-14 17:53
Tnx, I have successfully installed it after fideling with UEFI settings. Turning of all C states and etc.

**Comment by nagilum99** [comment] 2019-11-14 20:58
The certificate thing is an expected situation, as most servers use self-signed ones, but XCP-ng/XenCenter primarily expect a signed one to verify the source. Accept it and you're done.

You coul experiment with the setting that was finally responsible to let you successfully install.
UEFI is mature by now, but it's still the cause for some flaws - and probably still will be for quite a while.
AFAIK it's often a problem of not being faulty on certain mainboards.
In most cases falling back to BIOS-Mode should have no drawbacks.

**Comment by DavorSaric** [comment] 2019-11-15 09:28
Hello, we are allready using XO Enterprise in business environment with paid licence. This is my private part. I jumped at conclusion, XCP is too buggy on AMD Ryzen 5 3600, now it won't boot, probably due to Hetzner restored BIOS do original state. So if you plan to rent a server and install on it, be warned. You only have limited time with KVM which works buggy in the start (BIOS shows blue screen and no settings, they confirm is a bug) so don't recomment Hetzner(or at least do not recommend AX series)

**Comment by DavorSaric** [comment] 2019-11-15 10:09
Update: BIOS didn't changed, but I cannot boot XCP-NG anymore from the DVD, neither over KVM ISO or with ISO directly attached to USB. Neither netinstall or full iso work, BIOS and UEFI. Hetzner said other users also reported Xen is not working on this server so... no luck.

**Comment by nagilum99** [comment] 2019-11-15 13:49
Then it's probably specific to the mainboards they use in that series.
As you already said, you successfully installed XCP-ng, I wonder what happened.

Also: You can always re-request the "Lara" for another 2 or 3 hours for free or continue a longer period as paid service. I forgot what they charge then. I like their "Serverbörse", you can make good snaps, sometimes.

**Comment by DavorSaric** [comment] 2019-11-15 14:04
Could be. I wasted yesterday and most of today and gave up. KVM is free for 3h and then it disconnects, you can allways ask for another session of 3h which is free.

**Comment by valhallen282** [comment] 2019-11-30 13:09
I came here just to say that - switching to UEFI - non CSM mode on a Ryzen 5 2400G on an MSI A320M Pro-VD/S V2.0 allowed me to boot and reinstall my instance. 
![XCp-Ng](https://user-images.githubusercontent.com/25100086/69900971-9e509e00-13a0-11ea-9883-5a1d0a60542e.jpg)

**Comment by stormi** [comment] 2020-02-10 11:55
@rushikeshjadhav so, from forum feedback, this installer issue is still present on XCP-ng 8.1 beta.

Could you try to investigate and find out of there are patches for that in the linux kernel that we could backport to ours? It should not fail just because the amount of memory is 8 Gb.

**Comment by rushikeshjadhav** [comment] 2020-02-12 13:57
As I understand, this issue can be solved by change 8192 value to 2048 while boot up and install. Can someone confirm whether its installation only issue or general runtime as well?

**Comment by nagilum99** [comment] 2020-02-13 18:09
Beside you could read the thread and links carefully before experimenting with such things: Yes and Install.

**Comment by rushikeshjadhav** [comment] 2020-02-14 07:40
Quoting would have helped. There seems no error information from regular or serial console about what happened? 

For urgent resolution : The installer can be built with kernel 4.4 for home-lab and you may be able to even run your XCP-NG 8.1 with kernel 4.4 without issues.

Regarding upstream fixes, can someone with access to the hardware try [kernel-alt](https://github.com/xcp-ng/xcp/wiki/Alternate-kernel)?

**Comment by nagilum99** [comment] 2020-02-14 18:33
We would have pasted any errors, if we would have gotten them. The systems just freeze.

And as written: It's only for the Installer, the final system works flawlessly.
I'm very confused why you're writing that a kernel downgrade is an urgent solution, when we already found out that changing the boot option does the trick?
I guess you still didn't read the thread, instead burning time with trying to find a solution for something that already has a solution (as long as there's no final patch to update the package/image).
"XCP-ng 8.0 comes with an updated Kernel (4.19)" and a downstep is never a good option, as you might drop support for newer hardware and also not taking advantage of optimisations.

I'm not gonna test any alternative or older kernels on the system.

**Comment by stormi** [comment] 2020-02-18 10:01
What we'll try is to provide an installation ISO that uses `kernel-alt` by default. `kernel-alt` is just the base 4.19 kernel to which we apply all kernel.org patches from the 4.19 branch, so it should be quite stable by construction, though we can't give it as much QA as the main kernel receives. If it installs well, I expect it to run well without much risks.

**Comment by DavorSaric** [comment] 2020-02-18 10:24
Hi, will that fix the installation issues on AMD Ryzen 5 3600  line of CPU's? If you want, you can test those at Hetzner, they offer 14days server cancellation free with no charge. I have tried before but installer just hangs and some panics or cpu hang errors pop up during boot. Tried a lot of things, changed bios/uefi settings and etc. Managed to boot one time and install XCP-ng and it worked. But after full format of disks I tried to install it again but it failed. Tried all the steps as before but no success. Seems like xcp-ng is currently very buggy to install on Ryzen. Could be to some combination of motherboard and cpu, I don't know. But if XCP-ng would support Ryzen, that would be awesome :)

**Comment by stormi** [comment] 2020-02-18 10:27
Have you tried the workaround that consists in changing the grub boot command (in UEFI mode) and reduce the amount of RAM on that line before booting? It works for others.

About kernel-alt, we don't know yet if that will fix anything. One assumption is that it could be a kernel bug that makes it not cope with 8Gb of memory in the system, so we want to test with the latest upstream patches.

**Comment by stormi** [comment] 2020-02-18 10:31
(Sorry, re-read the thread and I see that you've done that already)

**Comment by Linh1706** [comment] 2020-02-26 16:06
ryzen 2700x also have same issue.
ISO gives some initial boot messages, but eventually gets stuck with black screen.
CPU Ryzen 2700x
MOBO X470 TAICHI
RAM 32GB

**Comment by pblakez** [comment] 2020-02-27 02:38
Note I have installed on 6 ryzen5 systems now the changing the memory in
the grub menu works but the grub menu disappears too quickly and that may
be why people are having problems

Also gigabyte motherboards must have the latest bios or may not work
properly with later Ryzen CPU

**Comment by nagilum99** [comment] 2020-02-27 03:10
BIOS versions for CPU support are independend of XCP and thus a completely different topic.
Also we gave 2 options: either edit on runtime or edit the config file (USB-installs make it easy to do it). If you're too slow to edit it during runtime: Edit the config. Especially when installing multiple systems it makes no sense to do it the runtime way.

**Comment by nagilum99** [comment] 2020-02-27 03:15
Also @stormi: I could test if the boot-image works without the workaround, if you supply a modified image with alt-kernel.

**Comment by MrWaste** [comment] 2020-03-03 01:58
Dear, @nagilum99 
I just bought / built a computer last night.  CPU Ryzen 2700x, motherboard Asrock B450 Pro4, 23GB of Ram inside right now, have 32GB Max.

I am having the same problem as Linh1706 is having and I have no idea to fix this even with the 2 bypasses. I don't even know what that even is or how to do that. I have read the entire post from day one and still don't understand what I should do. 

"ISO gives some initial boot messages, but eventually gets stuck with black screen."
One message says "AMD processor family is NOT supported"

Is VPMU suppose to be disabled or should enable it?

Could you give a list of directions on what to do? Like Step by Step?

Thanks, 

Mr. Waste

**Comment by Linh1706** [comment] 2020-03-03 02:11
> Dear, @nagilum99
> I just bought / built a computer last night. CPU Ryzen 2700x, motherboard Asrock B450 Pro4, 23GB of Ram inside right now, have 32GB Max.
> 
> I am having the same problem as Linh1706 is having and I have no idea to fix this even with the 2 bypasses. I don't even know what that even is or how to do that. I have read the entire post from day one and still don't understand what I should do.
> 
> "ISO gives some initial boot messages, but eventually gets stuck with black screen."
> One message says "AMD processor family is NOT supported"
> 
> Is VPMU suppose to be disabled or should enable it?
> 
> Could you give a list of directions on what to do? Like Step by Step?
> 
> Thanks,
> 
> Mr. Waste

I fixed it by changing parameter from 8194M to 2048M
I don’t know which works, but other than editing the grub.cfg, i also edit the file isolinux.cfg
It’s at boot>isolinux>isolinux.cfg

You can try editing this file first, if still not working, then try edit both grub.cfg file that you can find in your usb.

**Comment by olivierlambert** [comment] 2020-03-03 06:53
Note that a new ISO will be out soon with a select choice to boot with "compatible" memory settings for Ryzen CPUs

**Comment by MrWaste** [comment] 2020-03-03 23:16
How long do you think before that will actually happen @olivierlambert ?

**Comment by MrWaste** [comment] 2020-03-03 23:45
Thank You all for your Help!! I finally worked, THANK YOU AGAIN!!

**Comment by stormi** [comment] 2020-03-10 15:08
XCP-ng 8.1 RC is out, with two new installer options offered at boot time. Please test both and report:
* boot with the alternate kernel
* boot with only 2G of RAM max

**Comment by stormi** [comment] 2020-03-27 15:42
So, people, we've put a lot of work to offer two new installer options and I really would like to get feedback before monday from people who had issues with their Ryzen APUs.

So, could anyone please boot the latest ISO (named prefinal3 here: https://updates.xcp-ng.org/isos/8.1/) and try:
* booting with the alternate kernel (in UEFI mode, that's simply a new boot menu entry. Else F2 for advanced options then type `install-alt`)
* booting with the new "2G RAM max" option (in UEFI mode, that's simply a new boot menu entry. Else F2 for advanced options and then type `install-2G`)

No need to perform the installation: just see if the installer starts when it gave a black screen previously.

**Comment by Linh1706** [comment] 2020-03-27 16:00
Let me try it and get you the result in 1 day. 
in the meantime, I'm investigating a Man-In-The-Middle attack for a client. 
anyone has experience in this pls let me know tho. tks

**Comment by nagilum99** [comment] 2020-04-03 01:46
Interestingly: I tested the standard install (just press enter) as the alternate kernel.
Both booted into the TUI on an AMD Ryzen 3400G. So I didn't try the 2G-version.
Didn't test it on multiple machines though.

**Comment by Linh1706** [comment] 2020-04-05 07:28
So I update my machine today.
With the condition that I changed the graphic card, and It currently doesn't recognize VMs correctly as stated above, using the normal boot and option, then after updating, restart and the screen is black, with a cursor blinking.
I'm trying to restore from backup and go with 2G option now

**Comment by olivierlambert** [comment] 2020-04-05 09:08
@Linh1706 if you have no internet connection nor NTP configured, this is normal. Please wait up to 10 minutes.

**Comment by Linh1706** [comment] 2020-04-05 09:17
Oh. damn I waited about 5 min and then did the clean install.
Now I am recovering the disk and VMs

The only thing I wish I could is test the upgrade whether it fix the GPU swap or not. Now I would not be able to test it, at least for a while.

**Comment by commandline-be** [comment] 2020-05-18 00:01
confirmed not working on AMD Ryzen 1700x.

Can this not simply be resolved with an AMD boot entry in grub ?

**Comment by stormi** [comment] 2020-05-18 06:36
> confirmed not working on AMD Ryzen 1700x.
> 
> Can this not simply be resolved with an AMD boot entry in grub ?

Have you tried the already available boot options I described above?

**Comment by commandline-be** [comment] 2020-05-18 08:58
> > confirmed not working on AMD Ryzen 1700x.
> > Can this not simply be resolved with an AMD boot entry in grub ?
> 
> Have you tried the already available boot options I described above?

Yes, the system boots the reboots, every time. I disabled Global c-states in the bios, supplemented boot options such as iommu=pt amd_iommu=on to no avail. System is set to UEFI als legacy+uefi to no avail. 

MSI X370 chipset with latest bios and AMD 1700x CPU.

**Comment by olivierlambert** [comment] 2020-05-18 09:10
Also it's possible you have the first batch of Ryzen with a known Linux CPU bug.

**Comment by commandline-be** [comment] 2020-05-18 09:17
> Also it's possible you have the first batch of Ryzen with a known Linux CPU bug.

I think i checked and the CPU is not of that batch. Also, i believe a workaround was introduced in later kernels ?

**Comment by commandline-be** [comment] 2020-05-19 20:17
SOLVED - for X370 chipset with 8 core CPU (1700x)

kernel boot parameters: iommu=on amd_iommu=on 
optionally also add: rcu_nocbs=0-15

BIOS configuration for CPU features is best set to enabled as a default instead of AUTO or disabled. Such as.

boot mode select: legacy+uefi
ErP ready: enabled
Core performance boost: disabled

> CPU Features (here typically set to enabled by me instead of auto, just works, better) found stable
Global C-state control: disabled
Power Supply Idle control: Auto
P-State Adjustment : Pstate 0
Precision Boost Overdrive: AMD Default
Mode0: enabled

**Comment by nagilum99** [comment] 2020-05-19 21:44
I never had a reason to disable C-States on AMD Ryzen CPUs, be aware: If the server is not fully loaded, it increases powerconsumption and lowers frequency on the used cores.

WARNING: ErP Enable disables WOL - in case someone might wants to use it!
That option anyways should only affect power usage (means which parts of the system still get power when it's "off") when system is shutdown, so it shouldn't be able to influence anything while the system is running.

**Comment by olivierlambert** [comment] 2020-05-20 08:08
Thanks for the feedback @commandline-be 

Did you find the smallest working set of options?

**Comment by commandline-be** [comment] 2020-05-24 09:04
> Thanks for the feedback @commandline-be
> 
> Did you find the smallest working set of options?

Not really. After i learned there is just one reason which actually works well. Setting the XMP profile from 2 (3200) to 1 (2933) Mhz. The system is running with 4 DIMM instead of 2 since recently. This appears to have created issues leading to instability. 

None of what i read about the issues leading to the segfaults, "bad ram" and so on was true.

In the end i did not continue with XCP-NG because it is not a very inviting platform. One at the web interface i felt at a loss to figure out how to work with it. If i ever have spare hardware i will consider to explore xcp-ng more as i think highly of the XEN hypervisor.

**Comment by nagilum99** [comment] 2020-05-24 14:21
RAM-OC is an absolute no-go for a stable server platform. First thing if your platform is unstable: Always undo any OC/performance optimizing stuff that is leaving the standards.
The 1700X is rated for 2666, not 3200. This _can_ work but is likely to be the root cause for any instabilities.

**Comment by commandline-be** [comment] 2020-05-28 12:09
I remember, back when i first installed it there was a bios upgrade which fixed all glitched. I guess there was regression in more recent BIOS. The 3200Mhz is through an XMP profile, no real OC involved. At least imho. Anyway, more reasons to considerd a 3700X or 4700X.

**Comment by nagilum99** [comment] 2020-05-28 14:01
The 1700X is rated for 2666 MHz (effective) DDR4.
If you load a Profile for 3200 MHz, you _are_ OCing (there is no "real" or false") your CPUs memory controller.
XPM is loading settings from a table, stored in the SPI on the memory modules - which only describe the capabilities of the memory modules. They don't care for anything else.

In result, you can get memory errors, which can end up in various results: crash, reboot, corrupted data on storage...
As Xen is overwriting all memory at boot time (to make sure there's nothing bad hidden to compromise your system) it's likely that it's responsible for the reboots.

Can, but musn't. In any case: If you have any problems, make sure your machine is operating at parameters the vendors allow.

**Comment by commandline-be** [comment] 2020-05-28 14:36
I cannot but agree based on trial and error. Running memtest clearly shows zero or close to zero errors at lower speeds. To be honest, it took me some time to figure out. Given i ran at XMP 3200Mhz for well over a year without an issue. Difference being, then there were 2 DIMM slotted, now 4.

Thanks anway. Good point you made here.

**Comment by nagilum99** [comment] 2020-05-28 15:58
Memtest is special to treat: If it brings errors, there's definately a problem.
If it doesn't, it's not a guarantee that it's okay. It catches many, but not all defects. But if you have "close to zero" your system is definately broken. Also: If it worked THEN... is like "my shares went well last decade".
Transistors wear out. There's a good reason AMD didn't specify the first Gen for higher mem-speeds. Also 4 DIMs make a huge change for the bus. It's quite complex if you dig down deeper than normal endusers do. Some server CPUs e.g. are specified for different memory speeds, depending on the number of ranks/modules installed. The more the lower. But that's all not XCP-ngs fault. ;-)

**Comment by commandline-be** [comment] 2020-05-28 16:14
Hmm. Well, yeah. I vaguely remember when i kind of dug in to that topic it is so as you say.

Well. It was a struggle between proxmox and xcp-ng. For now it is proxmox, thinking already how to work with xcp-ng if i find more hardware. High on my list is also smart-os, but they do not support AMD for some mind boggling reason. 

With a small budget performance is key to me. Just 8 cores and 32 gb of ram, 1.2 TB SSD. Good enough for my needs, for now. We can go on, off course, for now i consider this topic closed for what i am concerned.

**Comment by stormi** [comment] 2021-02-15 16:49
Could some of you update us on this topic regarding XCP-ng 8.2? I'm specifically asking about the original issue, that is the unability to boot the installer without using the dedicated boot options we added.
* Does the default boot option work?
* Does the "2G" boot option work?
* Does the "alternate kernel" boot option work?

We want to know whether the 2G boot option is still necessary, and if it is, whether the alternate kernel solves the issue. If it does then we could go look for kernel patches that fix the boot.

**Comment by stormi** [comment] 2021-03-09 18:05
Ping. Feedback still needed :)

**Comment by stormi** [comment] 2021-03-09 22:20
Thanks. So it may be that the 2G option has become unnecessary and that the original issue reported against XCP-ng 8.0 has been solved?

**Comment by nagilum99** [comment] 2021-03-09 22:27
Looks like. Let's say "for now", not sure what it may be good for, in the future.
(If it helps: 1x 8 GB module installed)

**Comment by olivierlambert** [comment] 2021-03-09 22:30
Thanks for the feedback @nagilum99

**Comment by stormi** [comment] 2021-03-10 10:43
So, unless someone finds through tests that the 2G option remains useful, I'll remove it from next XCP-ng release and will close this issue.

**Closed** 2021-03-31 17:13 UTC
Labels: bug :bug:, version:8.0, xenserver_bug

**Comment by redowk** [comment] 2021-12-13 11:47
official 8.2.0 image, usb install.
Ryzen Threadripper PRO 3945WX (Lenovo P620)
tried standard / 2G option / alt kernel to no avail :|

**Comment by olivierlambert** [comment] 2021-12-13 12:02
Any diff using BIOS/legacy boot?

**Comment by stormi** [comment] 2021-12-13 12:06
I suggest a new issue be created (and linked from here), as it seems to be different from the previous one.

**Comment by redowk** [comment] 2021-12-13 14:48
done, indeed looks diferent:
https://github.com/xcp-ng/xcp/issues/530

**Comment by vbware** [comment] 2023-07-02 15:04
Greetings. I have tried several versions, 8.0, 8.1, 8.2 and they fail with new BIOS on motherboards. 
The xcp-ng v8.3, that is under development, WORKs and avoids the black screen in the xcp-ng installation process.
But I have tried changing 2048M on v8.2 install, but it doesn't work. I change vga to vga_text but doesnt work.
I can only contribute that I have seen that the version of GRUB between one version and another are v.2.0.6 (xcp-ng v8.3) and v.2.0.2 (xcp-ng v8.2) are different.
The bug could be fixed (perhaps), if the 8.2 image were mounted with a later version of GRUB. (v2.0.6), like GRUB xcp-ng v8.3.
I'm not sure, but who knows...

Hardware: Asus b760mk + i5

**Comment by nagilum99** [comment] 2023-07-02 15:23
"Motherboards"? Does it affect multiple? All same type?
Which BIOS (Firmware version)?
NEW means old one works?
Alwasy give very precise infos. BIOS version, exact CPU type (socket 1700 can have 2 gens etc.)

It's usually the Kernel, not grub, that is causing the problem.
You could additionally try these:
noapic acpi=off

The mem=2048 was, till now, primarily an AMD APU problem.

Does 8.3 boot AND also run after install?

**Comment by vbware** [comment] 2023-07-02 16:31
> Greetings. I have tried several versions, 8.0, 8.1, 8.2 and they fail with new BIOS on motherboards. The xcp-ng v8.3, that is under development, WORKs and avoids the black screen in the xcp-ng installation process. But I have tried changing 2048M on v8.2 install, but it doesn't work. I change vga to vga_text but doesnt work. I can only contribute that I have seen that the version of GRUB between one version and another are v.2.0.6 (xcp-ng v8.3) and v.2.0.2 (xcp-ng v8.2) are different. The bug could be fixed (perhaps), if the 8.2 image were mounted with a later version of GRUB. (v2.0.6), like GRUB xcp-ng v8.3. I'm not sure, but who knows...
> 
> Hardware: Asus b760mk + i5

Greetings.
It took a while, but I found the problem: The error occurs with new BIOS and integrated GPUs.
Because the mounting of the ISO is done with GRUB v2.02 (?? i think), once the installation process starts, the system is not able to use (for some reason) the integrated GPU in the I5 15000 for example.
The solution is to modify the boot GRUB (since I have tested it with the xcp-ng v8.3 (GRUB v2.06) and it works with the integrated GPU).
By having the integrated GPU, the BIOS does not allow to activate compatibility CSM, and therefore, it does not load the VGA correctly.
The solution has been to simply use an additional PCIe graphics card, then enter the BIOS (Asus b760mk), activate the installed main graphics card and activate the CSM compatibility.
It has worked for me, and I am convinced that the problem lies in the GRUB boot (older version), which is not able to use the integrated VGA.
If you were to remount the xcp-ng v.8.2 ISO image by changing the GRUB version back to v8.3, the problem would be fixed.
I hope this helps others.
(Sorry, I tried to explain myself as best as possible)

**Comment by vbware** [comment] 2023-07-02 16:35
Motherboard: ASUS B760M-K
Micro: Intel I5 13400 with GPU integrated
BIOS version:  v04.07 (Build: 11/12/2022)

**Comment by vbware** [comment] 2023-07-02 16:39
> ¿"Placas base"? ¿Afecta a varios? ¿Todos del mismo tipo? ¿Qué BIOS (versión de firmware)? ¿NUEVO significa que el viejo funciona? Siempre da información muy precisa. Versión de BIOS, tipo de CPU exacto (el zócalo 1700 puede tener 2 generaciones, etc.)
> 
> Por lo general, es el Kernel, no grub, el que está causando el problema. También puedes probar estos: noapic acpi=apagado
> 
> El mem=2048 era, hasta ahora, principalmente un problema de la APU de AMD.
> 
> ¿Arranca 8.3 Y también se ejecuta después de la instalación?
> 
> También: ¿arrancar en modo BIOS/CSM o UEFI? ¡Esto también hace diferencias y puede resolver problemas (no limitado a xcp-ng)!

Thanks, now MODE UEFI ....CSM = UEFI + OPROM old...Legacy only..

**Comment by vbware** [comment] 2023-07-02 16:49
> > Saludos.  He probado varias versiones, 8.0, 8.1, 8.2 y fallan con nueva BIOS en placas base.  El xcp-ng v8.3, que está en desarrollo, FUNCIONA y evita la pantalla negra en el proceso de instalación de xcp-ng.  Pero he intentado cambiar 2048M en la instalación de v8.2, pero no funciona.  Cambié vga a vga_text pero no funciona.  Solo puedo aportar que he visto que la versión de GRUB entre una versión y otra son v.2.0.6 (xcp-ng v8.3) y v.2.0.2 (xcp-ng v8.2) son diferentes.  El error podría solucionarse (quizás), si la imagen 8.2 se montara con una versión posterior de GRUB.  (v2.0.6), como GRUB xcp-ng v8.3.  No estoy seguro, pero quién sabe... 
> > Hardware: Asus b760mk + i5
> 
> Saludos. Me tomó un tiempo, pero encontré el problema: el error ocurre con el BIOS nuevo y las GPU integradas. Debido a que el montaje de la ISO se realiza con GRUB v2.02 (?? creo), una vez que comienza el proceso de instalación, el sistema no puede usar (por alguna razón) la GPU integrada en el I5 13400 (13th gen) para ejemplo. La solución es modificar el GRUB de arranque (ya que lo he probado con el xcp-ng v8.3 (GRUB v2.06) y funciona con la GPU integrada). Al tener la GPU integrada, la BIOS no permite activar la compatibilidad CSM, y por tanto, no carga correctamente la VGA. La solución ha sido simplemente utilizar una tarjeta gráfica PCIe adicional, luego entrar en la BIOS (Asus b760mk), activar la tarjeta gráfica principal instalada y activar la compatibilidad CSM. Me ha funcionado, y estoy convencido de que el problema radica en el arranque de GRUB (versión anterior), que no es capaz de usar el VGA integrado. Si tuviera que volver a montar la imagen ISO xcp-ng v.8.2 cambiando la versión de GRUB a v8.3, el problema se solucionaría. Espero que esto ayude a otros. (Perdón, traté de explicarme lo mejor posible)

----
Wow, I sang victory ahead of time.
now in the installation process the network card is not detected (v8.2)

**Comment by nagilum99** [comment] 2023-07-02 17:24
Plz stop insisting on GRUB, as long as you don't know.
Even it it's still an old mainversion kernel, it's getting patched all the time, backporting changes from newer kernels.
Grub is NOT the probem in 99.9 % of the cases. Especially if you can see it's menu!
It next tries to boot a Linux kernel and since you're trying an old 8.2 ISO with a rather new iGPU/CPU, it's for very sure the kernel and missing driver/compatibility for your HW.

It's always tricky to use the newest hardware on older images, especially if it's not made/focussed to run on consumer hardware.
Remember: Even if it's running on many platforms and Vates (and other developers) try to push compatibility: The main focus is clearly what company use: Servers.
That's also reasoned by Citrix, as the company doing the main part of XenServer development, which is a base for xcp-ng.

That your NIC is now unsupported is also adding to this point: Too new HW for kernel, no support.

**Comment by nagilum99** [comment] 2023-07-02 17:26
I don't know if the 8.2 installer is able to already boot alternate kernel, you could try that one.
Alternatively: You could try to build your own ISO, using a more modern kernel (not touching grub)

**Comment by vbware** [comment] 2023-07-03 15:08
> Por favor, deja de insistir en GRUB, mientras no lo sepas. Incluso si todavía es un kernel de versión principal antiguo, se está parcheando todo el tiempo, retroalimentando los cambios de los kernels más nuevos. Grub NO es el problema en el 99,9% de los casos. ¡Especialmente si puedes ver su menú! A continuación, intenta iniciar un kernel de Linux y, dado que está probando un ISO 8.2 antiguo con una iGPU/CPU bastante nueva, es muy seguro que el kernel y el controlador/compatibilidad que faltan para su HW.
> 
> Siempre es complicado usar el hardware más nuevo en imágenes más antiguas, especialmente si no está hecho/enfocado para ejecutarse en hardware de consumo. Recuerde: incluso si se ejecuta en muchas plataformas y Vates (y otros desarrolladores) intentan impulsar la compatibilidad: el enfoque principal es claramente lo que usa la empresa: servidores. Eso también es razonado por Citrix, ya que la empresa realiza la parte principal del desarrollo de XenServer, que es una base para xcp-ng.
> 
> El hecho de que su NIC ahora no sea compatible también se suma a este punto: Demasiado nuevo HW para kernel, sin soporte.

thanks! and sorry!
