### ISSUE TITLE
VMs backed-up (snapshot/export) results in random VM, sometimes, dead

### ISSUE THREAD

**Issue by ezaton** [xcp-ng/xcp#351] opened 2020-03-14 15:34 UTC
Hi.
We use Xackup for a large pool backup. We have a pool of 8 hosts, and ~130 VMs. When performing Xackup backup - which creates a new snapshot of VM disks, and in our case - performs delta export and 4 parallel workers, sometimes one or two of the VMs "dies" and we cannot bring it up because VDI is reported locked. I need to run vdi-forget, and then sr-scan and recreate the vbd and only then there is a fair chance that the VM will start. In some cases, it will start only(!) on the original host on which it was running.
This is an LVMoiSCSI SR, with multipath enabled. There are no known network issues, however, performance, in general, is sub-optimal - and could be related to the huge amounts of coalesce tasks at hand (it runs only one at a time, but it has about 300 still to go after a whole week without backups!).
XCP-ng version 8.0 with the latest updates. This has happened several times already. 
Attached are SMlog and xensource.log files from the entire cluster, for this specific VM.
The VM name is Ohad_marketing, with UUID ced1acf0-ef1b-97d6-13e9-8402fc6ab541. The VDI in problem is ced1acf0-ef1b-97d6-13e9-8402fc6ab541. Around 12:30 (noon) I have attempted to start it (and got VDI unavailable). Then I have called vdi-forget, and then sr-scan and recreated the vbd. 
Pool master is xen101-r430. The VM resided on xen107-R630 server before its untimely death. 
There are no IO errors on the host(s) and there is no indication of a problem on other VMs (two VMs which got this problem. One of them had a huge interference by the standby admin, which did no good). The VM went through soft reboot at about 3AM, and then at 10:45 soft reboot, and then hard reboot. 
The result was locked VDI, and unclean removal. And I do not know the reason for that.
I would appreciate help - both in further identifying the what to provide, and finding a remedy/workaround.

Thanks!
[SMlog.txt](https://github.com/xcp-ng/xcp/files/4332941/SMlog.txt)
[xensource.log](https://github.com/xcp-ng/xcp/files/4332942/xensource.log)

**Comment by ezaton** [comment] 2020-03-14 15:35
A note - the log files show *only* the relevant VDI and VM uuid from all pool members. If there is anything else required - please let me know and I will provide it.
Thanks

**Comment by stormi** [comment] 2020-03-20 11:03
Hi. That kind of analysis is something that we do through XCP-ng support contracts. Else it's "when time allows" or help from the community (which you'd probably reach more efficiently on the forum).

I haven't looked at the logs yet, may do later. One piece of information: the coalesce management algorithm has been improved in 8.1. However, there may be an underlying storage issue that is the root cause.

**Comment by stormi** [comment] 2020-04-20 09:52
A quick look at the logs did not give me much ideas. I see a `VDI_NOT_AVAILABLE` error which may indicate underlying storage issues, but it could also be software-related.

Closing this issue since support should happen first either on the forum or through our support channels.

**Closed by stormi** 2020-04-20 09:52 UTC
