### ISSUE TITLE
XCP-ng 7.6 /run/lvm/lvmetad.socket: connect failed

### ISSUE THREAD

**Issue by jaroslaw-freus** [xcp-ng/xcp#104] opened 2018-11-28 19:49 UTC
I've performed a fresh installation XCP-NG on HP DL 360 G10 server.

root@xcp-ng-n1 ~]# cat /etc/centos-release
XCP-ng release 7.6.0 (xenenterprise)

After successful installation I've destroyed local SR using below commands:
xe sr-list
xe pbd-list sr-uuid=<UUID>
xe pbd-unplug  uuid=<UUID>
xe pbd-destroy uuid=<UUID>
xe sr-forget uuid=<UUID>

I wanted to use LVM command to create custom SR's, but I can't use any of the LVM tooling.

[root@xcp-ng-n1 ~]# pvs
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
[root@xcp-ng-n1 ~]# vgs
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
[root@xcp-ng-n1 ~]# lvs
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.

I've found below topic on Citrix 
https://discussions.citrix.com/topic/398479-unable-to-start-vm-after-upgrade/

They suggest to set use_lvmetad = 0 in /etc/lvm/lvm.conf

XCP-NG configuration:
----
# Configuration option global/use_lvmetad.
        # Use lvmetad to cache metadata and reduce disk scanning.
        # When enabled (and running), lvmetad provides LVM commands with VG
        # metadata and PV state. LVM commands then avoid reading this
        # information from disks which can be slow. When disabled (or not
        # running), LVM commands fall back to scanning disks to obtain VG
        # metadata. lvmetad is kept updated via udev rules which must be set
        # up for LVM to work correctly. (The udev rules should be installed
        # by default.) Without a proper udev setup, changes in the system's
        # block device configuration will be unknown to LVM, and ignored
        # until a manual 'pvscan --cache' is run. If lvmetad was running
        # while use_lvmetad was disabled, it must be stopped, use_lvmetad
        # enabled, and then started. When using lvmetad, LV activation is
        # switched to an automatic, event-based mode. In this mode, LVs are
        # activated based on incoming udev events that inform lvmetad when
        # PVs appear on the system. When a VG is complete (all PVs present),
        # it is auto-activated. The auto_activation_volume_list setting
        # controls which LVs are auto-activated (all by default.)
        # When lvmetad is updated (automatically by udev events, or directly
        # by pvscan --cache), devices/filter is ignored and all devices are
        # scanned by default. lvmetad always keeps unfiltered information
        # which is provided to LVM commands. Each LVM command then filters
        # based on devices/filter. This does not apply to other, non-regexp,
        # filtering settings: component filters such as multipath and MD
        # are checked during pvscan --cache. To filter a device and prevent
        # scanning from the LVM system entirely, including lvmetad, use
        # devices/global_filter.
        use_lvmetad = 1
----
I've also had to change value of metadata_read_only to 0  

# Configuration option global/metadata_read_only.
        # No operations that change on-disk metadata are permitted.
        # Additionally, read-only commands that encounter metadata in need of
        # repair will still be allowed to proceed exactly as if the repair had
        # been performed (except for the unchanged vg_seqno). Inappropriate
        # use could mess up your system, so seek advice first!
        metadata_read_only = 1

Alternatively:
lvcreate -L 200G -n LS_VM2 /dev/VG_XenStorage-76ff6fc5-aee1-ba91-8d9e-abca83417df1 --config global{metadata_read_only=0}

After changing this I was able to use LVM tools.

BR,
Jaroslaw

**Comment by olivierlambert** [comment] 2018-11-28 19:57
Hi,

You shouldn't do any manual LVM operations. You should use SR creation command (from CLI or Xen Orchestra). What's your objective here?

**Comment by jaroslaw-freus** [comment] 2018-11-28 20:08
We have a EX server at Hetzner and I'd like for each person to have it's own SR. I'm doing this since XenServer 5.6 to XS 6.5 and it was working fine :)

**Comment by olivierlambert** [comment] 2018-11-28 20:16
This is not a good idea, I mean it's not meant to be used like that (but well, if you are sure about what you are doing, it's up to you). Anyway, playing with metadata could be dangerous.

I still don't get the real use case of having "one SR per user", now you can half self-service portals in XO for example. But you didn't tell us exactly what's your exact use case, so I probably missing your point :)

Alternatively, you could create extended partitions, and then create a local LVM SR using the normal way for each logical partition, this way you won't have to tinker the storage layer.

**Comment by jaroslaw-freus** [comment] 2018-11-28 21:15
Well it's possible that I'm using XenServer in the wrong way, but until it's working I down with that ;)

The use case is that one server is shared among users. Each user has fixed storage space for his use only. Life is easier that way for us :) Sorry I don't know how to put in another way. Maybe if you could ask more specific question?

Could you please share any link/doc's regarding extended partitions approach?

**Comment by olivierlambert** [comment] 2018-11-28 21:18
You use case is exactly answered by the self service feature of Xen Orchestra: https://xen-orchestra.com/docs/self_service.html

Otherwise, you can create extended partition (disk partitions), eg it would be `/dev/sda6`, `/dev/sda7` etc. Then for each one, create a local LVM SR (in XO: new/storage/Local LVM/device name = /dev/sda6)

**Comment by jaroslaw-freus** [comment] 2018-11-28 22:49
I can't use XO at this host due to limited resources, so I'm down to XenCenter/CLI. 

From my point of view there is no big difference between creating a SR on extended partition or on LVM.

I don't know that much about XEN to tell the difference. During last 7 years there was no difference for me, but I'm willing to learn/change my mind on this topic.

**Comment by borzel** [comment] 2018-11-28 23:45
> I can't use XO at this host due to limited resources

You have not even 5GB disk space and 2GB RAM for a ubuntu VM?

**Comment by jaroslaw-freus** [comment] 2018-11-29 12:20
Ok guys, for me there is no difference if I use EXT3 SR or LVM SR.

EXT3: 
- need to create several EXT3 partitions on free disk space
- xe sr-create name-label="Local SR" host-uuid=(uuid of host) type=ext device-config-device=/dev/<device path, usually it's sda3> shared=false content-type=user

LVM:
- need to create (out of free space) physical volume
- need to create volume group and several logical volumes
- xe sr-create name-label="Local SR" host-uuid=(uuid of host) type=lvm device-config-device=/dev/<volume group> shared=false content-type=user

The issue is about that if I would like LVM (because I like it more), I've mentioned errors. The question is why I can't use LVM tools without the mentioned workarounds?

**Comment by olivierlambert** [comment] 2018-11-29 12:41
That's not correct. For LVM you don't need to create a PV/VG first, because another one will be added on top by XCP-ng. This is **NOT** a recommended way, **at all** (due to metadata handling). You can however, create your LVM SR directly on a partition (like for ext3).

So the issue is that you do an incorrect SR creation workflow.

**Comment by jaroslaw-freus** [comment] 2018-11-29 12:58
Got it. I'll give it a try.

Thank you.

**Comment by iServU** [comment] 2018-12-11 12:07
After upgrading from XCP-ng 7.5 to 7.6, the external HDD I use to backup VM's produced an error as I think to remember that is the located where I created a Local ISO SR.

Now it says Local ISO Images RSR is broken (unplugged), yet other vhdd's for VM's backup functions are accessible.

[root@xen01 ~]# lvscan -v
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
    Using logical volume(s) on command line.
    Found same device /dev/sdb with same pvid 86ayX0e2TuUptVpUVuzCxeFxNfk8Hfxc
  ACTIVE            '/dev/VG_XenStorage-70effabc-c5a3-34f1-8e7e-b2a317125a8e/MGT' [4.00 MiB] inherit
  inactive          '/dev/VG_XenStorage-70effabc-c5a3-34f1-8e7e-b2a317125a8e/VHD-b6c5000f-1a12-4a27-aaf1-a488cb8d9b78' [256.00 MiB] inherit
    Found same device /dev/sda3 with same pvid lLEPJYy3oc2TMgG3scXsiz2RtR84i0Db
    Found same device /dev/sdb with same pvid 86ayX0e2TuUptVpUVuzCxeFxNfk8Hfxc
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/MGT' [4.00 MiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-c3e935cb-af90-4ca8-846c-5da7bbc030c6' [11.81 GiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-96622423-435e-467a-8241-a88ec7746f63' [14.91 GiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-d957e6cb-5c3b-4207-a1b0-fea5a729367b' [14.61 GiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-091953c6-f642-439b-a21c-4c1aad166474' [72.77 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-fcdaeaa8-ecdb-4bc2-ae80-7d4a7308ddcf' [8.22 GiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-3bfcc971-7261-4f21-b649-2349ec0f3fd1' [60.00 MiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-0a46f4f8-fb43-489b-a2f6-42bb4d96b42e' [100.20 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-c881f7ee-8e94-4b94-a9cc-334614ae2410' [256.00 MiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-f9a61afc-8586-4ff8-9762-4d22cb2b99d8' [25.84 GiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-48b4939f-228e-4235-b109-57083cea7ff5' [60.12 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-bdaf2cba-afa4-40c1-8a3a-9c7ee753dcd3' [8.00 MiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-d4390e4b-d27b-4d54-bdac-74fdf3275a0e' [60.12 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-f1f6ae98-36aa-4a80-9ab6-02c7df10499c' [8.00 MiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-24ef45db-0ace-4087-a0ee-8ef5ca40baf0' [150.30 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-4d2783e3-8ab4-44a7-b820-2a634d56ac82' [8.00 MiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-f5cbe7f8-816c-4b1c-b643-ddd516d305e5' [150.30 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-0d83e148-2a76-41e9-826a-b07457916c9a' [8.00 MiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-f0f16481-cce0-49c1-b544-fba580559d99' [60.12 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-c994aee5-8042-4e1e-8d02-104924118b54' [8.00 MiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-85b5041a-9c5a-4d69-bcf8-c0cf595a259d' [751.47 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-21c4e2d8-238f-4457-9c67-9cc172d5e389' [8.00 MiB] inherit
  ACTIVE            '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-9163fe6c-e9e1-4688-8bfa-081b5185b720' [150.30 GiB] inherit
  inactive          '/dev/VG_XenStorage-b9722d08-b70c-681f-ea94-85204f44b6e7/VHD-125cdf5f-6362-4e82-8917-18e297e14bcb' [8.00 MiB] inherit

**Comment by gdelafond** [comment] 2018-12-12 09:13
I installed a fresh XCP-NG 7.6 and lvm tools gives me the same result.
I did not do anything after the installation.

Installation has been done with Soft RAID1 and selecting EXT SR type during the installation.

```
[root@localhost ~]# xe sr-param-list  uuid=6c9e4f19-eb57-60f7-5612-0bd150322f45
uuid ( RO)                    : 6c9e4f19-eb57-60f7-5612-0bd150322f45
              name-label ( RW): Local storage
        name-description ( RW):
                    host ( RO): localhost
      allowed-operations (SRO): VDI.enable_cbt; VDI.list_changed_blocks; unplug; plug; PBD.create; VDI.disable_cbt; update; PBD.destroy; VDI.resize; VDI.clone; VDI.data_destroy; scan; VDI.snapshot; VDI.mirror; VDI.create; VDI.destroy; VDI.set_on_boot
      current-operations (SRO):
                    VDIs (SRO):
                    PBDs (SRO): 7034d05e-a63f-2151-e437-94c2ce59840b
      virtual-allocation ( RO): 0
    physical-utilisation ( RO): 50343936
           physical-size ( RO): 42653220864
                    type ( RO): ext
            content-type ( RO): user
                  shared ( RW): false
           introduced-by ( RO): <not in database>
             is-tools-sr ( RO): false
            other-config (MRW): i18n-original-value-name_label: Local storage; i18n-key: local-storage
               sm-config (MRO): devserial:
                   blobs ( RO):
     local-cache-enabled ( RO): true
                    tags (SRW):
               clustered ( RO): false

[root@localhost ~]# xe pbd-param-list  uuid=7034d05e-a63f-2151-e437-94c2ce59840b
uuid ( RO)                  : 7034d05e-a63f-2151-e437-94c2ce59840b
     host ( RO) [DEPRECATED]: 7a26068a-678a-46cd-9fcc-1fabde2fdbb8
             host-uuid ( RO): 7a26068a-678a-46cd-9fcc-1fabde2fdbb8
       host-name-label ( RO): localhost
               sr-uuid ( RO): 6c9e4f19-eb57-60f7-5612-0bd150322f45
         sr-name-label ( RO): Local storage
         device-config (MRO): device: /dev/disk/by-id/md-name-localhost:127-part3
    currently-attached ( RO): true
          other-config (MRW): storage_driver_domain: OpaqueRef:b5f63c08-6e47-4fac-925d-398c59b6d3ed

[root@localhost ~]# pvs
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
  PV           VG                                              Fmt  Attr PSize  PFree
  /dev/md127p3 XSLocalEXT-6c9e4f19-eb57-60f7-5612-0bd150322f45 lvm2 a--  40.48g    0

[root@localhost ~]# vgs
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
  VG                                              #PV #LV #SN Attr   VSize  VFree
  XSLocalEXT-6c9e4f19-eb57-60f7-5612-0bd150322f45   1   1   0 wz--n- 40.48g    0

[root@localhost ~]# lvs
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
  LV                                   VG                                              Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  6c9e4f19-eb57-60f7-5612-0bd150322f45 XSLocalEXT-6c9e4f19-eb57-60f7-5612-0bd150322f45 -wi-ao---- 40.48g
```

**Comment by olivierlambert** [comment] 2018-12-12 11:35
Can you reproduce the issue? I mean, this couldn't happen with a default install or I missed something

**Comment by gdelafond** [comment] 2018-12-12 12:32
@olivierlambert the warning (at least) is present with the default install. (I have reproduced it a second times without soft RAID).

**Comment by olivierlambert** [comment] 2018-12-12 16:46
I don't get it, I'll take a look on a test system. Thanks for the feedback. @stormi can you reproduce?

**Comment by stormi** [comment] 2018-12-12 17:53
This is related to https://bugs.xenserver.org/browse/XSO-908 that I had reported, though I did not detect that it would cause a warning in lvm tools (but I was right in saying that it's a bad idea to have fresh install and upgraded systems behave differently).

The warning in itself is benign, from what I understand from the Citrix forum thread listed above.

Given the differences in behaviour, I'd say:
* 7.5 yum updated to 7.6: use_lvmetad=0, no warnings
* 7.5 upgraded to 7.6 via ISO: use_lvmetad=1, warnings
* 7.6 fresh install: use_lvmetad=1, warnings

**Comment by stormi** [comment] 2018-12-21 12:55
So, there a different issues in this bug report and we need to give it some clarity.
From what I understood, the "XCP-ng 7.6 /run/lvm/lvmetad.socket: connect failed" warning is a benign bug that doesn't have any consequence and will be fixed in the next releases of XenServer and XCP-ng. Issues reported in this bug report have this warning in common but are not caused by this warning, unless I'm proved wrong.

So I'm closing this bug report and invite everyone who still has issues to open a separate bug report for it. Thanks!

I'll open one for the warning itself.

**Closed by stormi** 2018-12-21 12:55 UTC

**Comment by stormi** [comment] 2018-12-21 13:02
Opened #114

**Comment by kenneth104** [comment] 2019-02-16 09:09
hava some 
I build local iso SR in xen5.x to xen 7.1 is OK

> lvcreate -L 10GB -n myiso VG_XenStorage-edd3649e-eae7-44e0-1453-8e16f02f347c --config global{metadata_read_only=0}
> 
> mkfs.ext4 /dev/XenStorage-edd3649e-eae7-44e0-1453-8e16f02f347c/myiso
> 
> mkdir /myiso
> 
> xe sr-create name-label=ISOs type=iso \
> device-config:location=/myiso/ ISOs \
> device-config:legacy_mode=true content-type=iso
> 
> vgchange -a y  --config global{metadata_read_only=0}    
> 
> mount /dev/XenStorage-edd3649e-eae7-44e0-1453-8e16f02f347c/myiso /myiso
