### ISSUE TITLE
Software RAID install ends up with blue screen

### ISSUE THREAD

**Issue by gallart** [xcp-ng/xcp#492] opened 2021-04-21 13:16 UTC
Trying to install XCP-NG 8.2 on NVMe software RAID.

After choosing disks + confirmation of erase, I end-up with dead blue screen :

![image](https://user-images.githubusercontent.com/2728195/115559857-5e9b9680-a2b4-11eb-8b84-de40b3ed77ab.png)

![image](https://user-images.githubusercontent.com/2728195/115559800-504d7a80-a2b4-11eb-95a6-dc406b2084ac.png)

Workaround : reboot and he detects existing RAID then I can go on, but Grub not configured at this moment, need to grub-install from rescue.

**Comment by gallart** [comment] 2021-04-21 13:17
Could find the error log :

![image](https://user-images.githubusercontent.com/2728195/115560158-9c98ba80-a2b4-11eb-8004-8abbe4871c1d.png)

**Comment by gallart** [comment] 2021-04-21 13:19
This might be helpful too :

![image](https://user-images.githubusercontent.com/2728195/115560482-ed101800-a2b4-11eb-8481-35e70df854d3.png)

**Comment by stormi** [comment] 2021-04-26 13:36
Hi. I've seen this too on software RAID, and not just on NVME. The installer is stuck in an endless loop until you reboot it and then it sees the created RAID array.

**Comment by stormi** [comment] 2021-04-26 13:38
Related forum thread: https://xcp-ng.org/forum/topic/4186/8-2-install-loops-on-software-raid

**Comment by stormi** [comment] 2021-05-25 13:38
We identified the cause. The loop happens when there are no other disks than the ones used in the software RAID and can be workarounded as you pointed earlier by rebooting the installer.

**Comment by stormi** [comment] 2021-05-26 10:10
The next installation ISOs we will produce will have the fix.

**Comment by benjamreis** [comment] 2021-07-06 10:26
Fixed by https://github.com/xcp-ng/host-installer/pull/27/

**Comment by stormi** [comment] 2022-03-23 12:18
Fixed in XCP-ng 8.2.1

**Closed by stormi** 2022-03-23 12:18 UTC
