### ISSUE TITLE
XCP-ng boot process stalled by ntpdate.service

### ISSUE THREAD

**Issue by bvitnik** [xcp-ng/xcp#216] opened 2019-07-01 23:30 UTC
There is a bug or an overlook in (presumably) all versions of XCP-ng (and XenServer 7.0 onward) that results in boot process being stalled for 70 seconds because of `ntpdate.service`. Boot process is stalled at switch over point when transitioning from splash screen to xconsole. Usually some noncritical messages from dmesg are shown at that time.

`ntpdate.service` is enabled by default and is started at boot time. It calls `/usr/libexec/ntpdate-wrapper` script which has this block:

```bash
while true; do
        /usr/sbin/ntpdate -U ntp -s -b $OPTIONS $tickers &> /dev/null
        RETVAL=$?
        [ $RETVAL -eq 0 ] || [ $retry -ge "$RETRIES" ] && break
        sleep $[10 * (1 << $retry)]
        retry=$[$retry + 1]
done
```

Call to `/usr/sbin/ntpdate` fails because `ntpd.service` is already started at that time and port 123 is bound. In `daemon.log`, this message can be seen:

`ntpdate[27314]: the NTP socket is in use, exiting`

This causes `RETVAL` to get value `1` and `sleep` to be called with increasing sleep time (10, 20 and finally 40 seconds) for a maximum of 3 retries resulting in boot process being stalled for 70 seconds.

Either `ntpdate.service` should be disabled (preferably) or `-u` option should be added to `ntpdate` command to use unprivileged port.

`/usr/libexec/ntpdate-wrapper` script seems to differ from the one supplied by CentOS (no sleep there, checked on version 7.6).

**Comment by nagilum99** [comment] 2019-07-02 00:54
I also noticed the delay and wonderes about it (respectively about no further messages for a while). Is it in the installer, too?

**Comment by stormi** [comment] 2019-07-02 09:54
Do you reproduce in XCP-ng 8.0? My test hosts do not show this behaviour, but I guess this may be related to a race condition.

**Comment by bvitnik** [comment] 2019-07-02 10:23
@stormi I did not try to install XCP-ng 8.0 so I cannot confirm.

**Comment by stormi** [comment] 2019-07-02 11:25
Here's the contents from `/usr/libexec/ntpdate-wrapper` from XCP-ng 8.0:

```
!/bin/bash

ntpconf=/etc/ntp.conf
ntpstep=/etc/ntp/step-tickers

[ "$EUID" != "0" ] && exit 4
[ -x /usr/sbin/ntpdate ] || exit 5
[ -f /etc/sysconfig/ntpdate ] || exit 6
. /etc/sysconfig/ntpdate

[ -f $ntpstep ] && tickers=$(sed 's/#.*//' $ntpstep) || tickers=

if ! echo "$tickers" | grep -qi '[a-z0-9]' && [ -f $ntpconf ]; then
        # the step-tickers file doesn't specify a server,
        # use servers from ntp.conf instead
        tickers=$(awk '$1=="peer"||$1=="server"{print $2}' $ntpconf | \
                grep -Ev '127\.127\.[0-9]+\.[0-9]+')
fi

if ! echo "$tickers" | grep -qi '[a-z0-9]'; then
        echo "NTP server not specified in $ntpstep or $ntpconf"
        exit 6
fi

/usr/sbin/ntpdate -U ntp -s -b $OPTIONS $tickers &> /dev/null
RETVAL=$?

[ $RETVAL -eq 0 ] && [ "$SYNC_HWCLOCK" = "yes" ] && /sbin/hwclock --systohc
exit $RETVAL
```

Looks like there's no sleep anymore, so I think it's fixed in 8.0.

**Comment by bvitnik** [comment] 2019-07-02 12:15
I've cross referenced `/usr/libexec/ntpdate-wrapper` in all of the versions of CentOS. `sleep` is present in all the versions up to 7.5. Version 7.5 (7.6 and 7.7 also) does not have `sleep` and that is what is used as a basis for  XCP-ng 8.0. So it seems that Citrix just used upstream ntpd package and it was fixed upstream in 7.5. CentOS users probably have not encountered this problem because `chronyd` is used by default.

**Comment by stormi** [comment] 2019-07-08 15:35
Closing since it is fixed in XCP-ng 8.0 and the bug is not critical enough for us to risk an update to 7.6. Thanks!

**Closed by stormi** 2019-07-08 15:35 UTC

**Comment by bvitnik** [comment] 2019-07-08 15:50
@stormi Should we make some note in XCP-ng wiki with a workaround `systemctl disable ntpdate.service`?

**Comment by stormi** [comment] 2019-07-08 16:18
Yes, maybe in the Known Issues page.

**Comment by bvitnik** [comment] 2019-07-08 22:54
I've added a note to Known Issues page on wiki.

**Comment by stormi** [comment] 2019-07-09 09:10
Many thanks
