### ISSUE TITLE
Dom0 memory demand is high alert even with 1GB+ of available memory

### ISSUE THREAD

**Issue by fabiorauber** [xcp-ng/xcp#41] opened 2018-06-01 13:01 UTC
I'm receiving many alerts like "_XenServer Alarm: Dom0 memory demand is high on "Control domain on host ETC"_. But if you log in and check the available memory, you can see there is more than 1GB of available memory for the Control Domain:

```# free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        2.4G        156M        9.5M        1.2G        1.2G
Swap:          1.0G        975M         48M
```
Is this the desired behaviour? Or should I increase the memory available for the control domain?

**Comment by stormi** [comment] 2018-08-29 10:10
Closing since it's not a bug or enhancement report. Please submit your question to the forum if not done already.

**Closed by stormi** 2018-08-29 10:10 UTC
