### ISSUE TITLE
PCI Passthrough issues with Linux Kernel v4.2 and newer

### ISSUE THREAD

**Issue by redorangefreak** [xcp-ng/xcp#560] opened 2022-07-13 17:59 UTC
This is a continuation of an issue discussed on the XCP-ng Forums. For any log entries or configuration details please go here: https://xcp-ng.org/forum/topic/6080/nvme-pci-passthrough-issues-with-el8

I have been using a setup for quite some time passing NVMe PCI devices through to Centos 7 guests on XCP-ng to run a few storage functions for systems I build/design. We recently started moving from Centos7 to AlamLinux8 and when it came time to do some testing/configurations for the new OS I am no longer able to successfully use the NVMe device being PCI passed through to the new guest OS. Long story short I tested several guest operating systems, verified drivers and changed servers/NVMe drives all with the same results if the guest Linux Kernel version was 4 or above. I brought in one of my hardware engineering friends to help me understand some of the MSI/MSI-X errors I was seeing in the guest dmesg and on guest boot and what he explained makes perfect sense that the issue was related to interrupts. Since MSI/MSI-X was not properly working, I was still able to interact with the NVMe device in the guest but at very very slow speeds (several minutes to write a partition table). My suspicions of this issue were confirmed  when I came across a VMware KB article (https://kb.vmware.com/s/article/2150585) describing the same behavior and the differences for MSI registration starting with Linux Kernel v4.2. It also includes a link to more details about the changes made to the Linux Kernel here: https://lkml.org/lkml/2015/4/13/21

I have only done testing with NVMe PCI passthrough but I suspect this could cause issues with any attempted PCI passthrough. I am happy to do more testing if needed.

**Comment by bryanvaz** [comment] 2022-08-04 17:10
Confirmed same issue also present on both Asrock Rack Intel C621 and AMD X470 boards with Intel P4510 drives.

@olivierlambert any success in getting Xen upstream acknowledge/prioritize the patch?

Trying to figure out how much support runway we have left on the old kernels before we're force to upgrade the guests and whether we need to make a lateral move to something that has a longer support timeline for kernel < v4.2.

@redorangefreak just wanted to confirm, your most recent working combo was:
* HOST: XCP-ng 8.2.1
* GUEST: CentOS 7.9

**Comment by olivierlambert** [comment] 2022-08-04 19:31
I had the opportunity to discuss with a Xen dev about this, and yes, it's possible we are experiencing this very issue.

A next step would be probably to make that known to upstream Xen in Xel devel mailing list, so this will get more attention. On our side, our bandwidth is pretty limited at the moment, but we'll see if we can hunt the problem and craft a solution collectively with the help of the Xen community :+1:

**Comment by redorangefreak** [comment] 2022-08-04 20:00
@bryanvaz Yes, latest working combination was XCP-ng 8.2.0/8.2.1 and CentOS 7.9 with the latest updates as of last week.

**Comment by bryanvaz** [comment] 2022-08-04 22:58
Agreed, doing a monkey patch downstream in xcp-ng for a change in the kernel does not really make sense since the issue will affect every Xen deployment with virtualized storage controllers (including a few large storage SI vendors). This should be handled at the Xen level, but the VMWare KB does not provide as much detail so it will definitely be a scavenger hunt unless one of the original Xen devs who wrote the PCI passthrough code is still around; the library that needs to be patched is probably 6-8 years old by now and has not been touched since (I wouldn't even know where to start looking).

I did a quick check, and all the major distros that still have some kind of LTS support and can be rolled back/upgraded to <v4.2 are already in maintenance mode and will end LTS arround 2024. These would be Ubuntu 14 LTS, CentOS 7, and Debian 8.

I have not checked to see what happens to the security patches if you pin the kernel to something as old as <v4.2, but I assume it would not be pretty.

**Comment by olivierlambert** [comment] 2022-08-05 16:25
I think we have enough "broader idea" of the issue:

* we know exactly since which kernel it appears
* VMware got a similar report explaining roughly what's the issue

With that, Xen developers could probably take a look and maybe ask for some debug to move forward.

**Comment by olivierlambert** [comment] 2022-08-06 09:02
So it means someone has to send a message on xen-devel ;)

**Comment by Daxcor69** [comment] 2022-09-09 01:40
I am about to embark on passing nvme drives to my vm.  Just to clarify, this issue is with the kernel version of the guest OS not the distribution i.e.  ubuntu.  Would this be the pci controller passthough, or would it also effect just the device pass through?

I am looking to create a nfs server vm, using physical nvme disks attached to the host.  As I understand for best performance I should ideally passthrough the controller, the next best would be to pass through the drives.

**Comment by redorangefreak** [comment] 2022-11-14 13:58
> I am about to embark on passing nvme drives to my vm. Just to clarify, this issue is with the kernel version of the guest OS not the distribution i.e. ubuntu. Would this be the pci controller passthough, or would it also effect just the device pass through?
> 
> I am looking to create a nfs server vm, using physical nvme disks attached to the host. As I understand for best performance I should ideally passthrough the controller, the next best would be to pass through the drives.

@Daxcor69 this issue seems to effect all pci devices I have tested with any of the newer guest kernels. Unfortunately, if you are using nvme disks, they may also present as pci devices just like your storage controller which will give you the same issue.

@olivierlambert @bryanvaz Have you guys seen any progress on this from Xen? Do you have a link to where it's being tracked? Is there anything I can do to help move things along?

**Comment by olivierlambert** [comment] 2022-11-14 15:41
I think we lack some logs to be able to open something. Would you mind to prepare something so I can push for it? (ie creating an issue on the "new" Xen Gitlab)

**Comment by adam-bramble** [comment] 2023-11-20 14:02
Hello, i have come accross this issue which seems to match what i am seeing, but looks like this is still an issue, is that correct?

**Comment by olivierlambert** [comment] 2023-11-20 14:41
Hi, check the tip on this paragraph:
https://docs.xcp-ng.org/compute/#2-tell-xcp-ng-not-to-use-this-device-id-for-dom0

This is probably your issue. Please confirm this fixes it. Then we will close it :)

**Comment by olivierlambert** [comment] 2023-11-20 20:59
Perfect, so to me this definitely check that the original issue is fixed thanks to this :+1:

**Closed by olivierlambert** 2023-11-20 20:59 UTC
