### ISSUE TITLE
Can't create new iSCSI (LVM) SR -  get error about GFS2 driver

### ISSUE THREAD

**Issue by sammcj** [xcp-ng/xcp#95] opened 2018-11-05 02:41 UTC
To reproduce:

1. Perform fresh install of XCP-NG 7.6, selecting default options when prompted.
2. Connect to newly installed host in XCP-NG centre
3. Attach SR, select iSCSI
4. Note than thinly provisioned LVMoiSCSI doesn't seem to be an option (offers GFS2 but is greyed out due to licensing)
5. Select the only option (Full provisioned LVM)
6. Enter Target, Scan for and select IQN and LUN
7. Click next and get error that the GFS2 driver is not found

Expected behaviour:

* User should be prompted to attach or format the LUN as LVMoiSCSI, then the SR to should be created and attached.

Screenshots:

![screen shot 2018-11-05 at 1 32 58 pm](https://user-images.githubusercontent.com/862951/47974951-e353c380-e0ff-11e8-80ec-5ade31da63fa.jpg)

_Note: The error in this screenshot is only shown after the below GFS2 error occurs and you dismiss the dialogue._
![screen shot 2018-11-05 at 1 33 05 pm](https://user-images.githubusercontent.com/862951/47975034-4d6c6880-e100-11e8-9f8e-e65651f13d8d.jpg)

![screen shot 2018-11-05 at 1 32 30 pm](https://user-images.githubusercontent.com/862951/47974944-df27a600-e0ff-11e8-9c85-4a11626bd52c.jpg)

**Comment by olivierlambert** [comment] 2018-11-05 08:36
1. Thin pro on iSCSI solution by Citrix (using GFS2) is **not open source**, so we can't redistribute it :disappointed: Be assured that we'll do our own in the future, trying to do something better in the meantime
2. I think you are not the first, can you create the issue on the XCP-ng Center repo? https://github.com/xcp-ng/xenadmin/issues/new/choose

> Note: adding a iSCSI SR should work in `xe` CLI or in Xen Orchestra

**Comment by SiCKTRiCKs** [comment] 2018-11-06 13:14
Same as my ticket #93, had the same error trying to add a local LVM thick on local raid card... unable to add any additionnal HBA storage.

**Comment by sammcj** [comment] 2018-11-07 00:10
@olivierlambert 

> Thin pro on iSCSI solution by Citrix (using GFS2) is not open source, so we can't redistribute it

That's OK, I'm not trying or wanting to use GFS2, this is simply iSCSI (LVM).

OK sorry it's not clear what is a XCP-ng centre bug and what is a XCP-ng bug unless you know what's actually broken.

I've copied the bug to https://github.com/xcp-ng/xenadmin/issues/116

**Comment by olivierlambert** [comment] 2018-11-07 09:37
Also, please use Xen Orchestra that works perfectly well with XCP-ng :p (because there is no Citrix stuff done in the middle :p )

**Comment by sammcj** [comment] 2018-11-07 09:38
Yeah I get where you’re coming from but it also requires installing a license which is _very_ off-putting.


--
Sam McLeod

**Comment by olivierlambert** [comment] 2018-11-07 09:39
What are you talking about? Install it from the sources, it's even in the official doc!! https://xen-orchestra.com/docs/from_the_sources.html

**Comment by olivierlambert** [comment] 2018-11-07 09:47
XO from the sources has no license system, all XO features are enabled.

What you get with XOA (Xen Orchestra virtual Appliance) is a turnkey system with one click updater, and pro support.

Up to you :)

**Comment by sammcj** [comment] 2018-11-07 09:54
Hmmm... ok...

I see the note on building it from the sources:

“WARNING 2: It's impossible to predict the result of a build for any Node and NPM versions. Please consider using XOA before trying to play with the manual build, which can be difficult if you are not used to NodeJS and NPM.”

FYI - My personal option as some looking at the viability of moving our organisation from XenServer to XCP-NG: If is that if there is a bug with xcp-ng centre with something as basic and mission critical as creating or attaching storage repositories I would expect that to be debugged and fixed (or rejected) rather than expected to install some JavaScript stuff from source to work around the issue.

I’m not having a go there, I’m just stating how I feel about this response as a potential user (or customer).

--
Sam McLeod

**Comment by sammcj** [comment] 2018-11-07 09:56
Hmmm... ok... I see the note on building it from the sources: “**WARNING 2: It's impossible to predict the result of a build for any Node and NPM versions.** Please consider using XOA before trying to play with the manual build, which can be difficult if you are not used to NodeJS and NPM.” FYI - My personal option as some looking at the viability of moving our organisation from XenServer to XCP-NG: If is that if there is a bug with xcp-ng centre with something as basic and mission critical as creating or attaching storage repositories I would expect that to be debugged and fixed (or rejected) rather than expected to install some JavaScript stuff from source to work around the issue. I’m not having a go there, I’m just stating how I feel about this response as a potential user (or customer).

**Comment by olivierlambert** [comment] 2018-11-07 09:58
If you are doing things seriously, you take commercial support with a turnkey product :wink: XO and XCP-ng couldn't exist as it today with enterprise customers paying for it. Home labers or companies without any budget can still use it, just having more time to understand what are they doing.

**Comment by sammcj** [comment] 2018-11-07 10:01
Well... I think that comment definitely speaks for itself.

> If you are doing things seriously, you take commercial support with a turnkey product 😉 XO and XCP-ng couldn't exist as it today with enterprise customers paying for it. Home labers or companies without any budget can still use it, just having more time to understand what are they doing.

**Comment by olivierlambert** [comment] 2018-11-07 10:05
Yeah, that's pretty clear. I think this is a dangerous thinking that you have, because it means only big corporations making money on your data can use money to build Open Source projects (React from FB for example).

Without any money, we couldn't pay the half-dozen developers working on XO, and it will be the same for XCP-ng team.

So clearly, I don't see your point. It's a fair deal: you can have all features for free, but not the support and the turnkey solution.

**Comment by sammcj** [comment] 2018-11-07 10:06
I didn’t ask for support. I logged a bug and the solution was ‘don’t use it’.

**Comment by olivierlambert** [comment] 2018-11-07 10:07
This is an Open Source project mate. A bug is created, and a volunteer (@borzel ) will try to fix it when he can.

**Comment by stormi** [comment] 2018-11-07 10:08
About the original bug report, there *will* be effort from those who maintain XCP-ng Center to fix it, and if the root cause appears to be in XCP-ng we're not going to say "we don't care, use XO".

So I think you misunderstood the advice to use XO here for "there will be no fix".

Closing since there's now https://github.com/xcp-ng/xenadmin/issues/116

**Closed by stormi** 2018-11-07 10:08 UTC
Labels: test needed

**Comment by sammcj** [comment] 2018-11-07 11:02
Olivier and I had an offline conversation as I felt this conversation wasn’t overly productive.

I think I misunderstood the intent of Oliviers comments to mean that the fix was to not use xcp-ng centre and instead to run Xen Orchestra from source, Olivier than clarified for me that he actually mean this as an alternative to see if it worked around the issue for me.

I didn’t expect support for the software and was trying contribute by logging a bug but perhaps I didn’t word it correctly and I believe this came off as me sounding like I was expecting support without paying (contributing) to the project. 

Olivier and I have clarified what we both intended with our comments and it’s clear we both misinterpreted each others intent. Im going to try to further debug the issue while knowing that I can run XO from source if I need a workaround / alternative. 

I’m pleased to hear that the xcp-ng centre bug report will be worked on as it sits within the projects priorities (which was my (perhaps mis communicated) intent).

**Comment by stormi** [comment] 2018-11-07 11:05
Thanks for that message :+1:

**Comment by olivierlambert** [comment] 2018-11-07 11:05
Thanks @sammcj 

Yes, I confirm that I never intended to tell that the definitive fix was to use XO, I was indeed trying to explain that it worked in XO (so you can add easily a SR from a decent UI if you can't wait for a fix in XCP-ng), which is available for free.

Extra note: you can create a shared SR even using XOA Free, which doesn't require any knowledge to deploy/install! (I think I forgot to mention that!)

**Comment by slamj1** [comment] 2018-11-10 03:04
Ran into this as well with XCP_NG Center. If you don't want to install XO from source here are the steps for adding the iSCSI SR (for the pool) with the CLI:

1) On any pool member at the console run (Note if you use CHAP, add device-config:chapuser="user" device-config:chappassword="password" to each of these commands):

       xe sr-probe type=lvmoiscsi device-config:target=[Your SAN IP address]

This should give some output in XML format and the piece we're interested in is the TargetIQN:

                 <TargetIQN>
                             iqn.2018-11.com.saasycloud.n8880u-10g:iscsi.thecus3.raid0
                 </TargetIQN>

2) Use the TargetIQN in the next command to get the SCSIId info:

      xe sr-probe type=lvmoiscsi device-config:target=[Your SAN IP Address] device- 
      config:targetIQN=iqn.2018-11.com.saasycloud.n8880u-10g:iscsi.thecus3.raid0

E.g.:
    <SCSIid>360014055fg54daa37104d478f2f7e3a2</SCSIid>

3) Now use the SCSIId value to add the SR to the pool:

       xe sr-create name-label="Lun02" type=lvmoiscsi shared=true content-type=user device- 
      config:target=[YourSAN IP Address] device-config:port=3260 device-config:targetIQN=iqn.2018- 
      11.com.saasycloud.n8880u-10g:iscsi.thecus3.raid0 device- 
      config:SCSIid=360014055fg54daa37104d478f2f7e3a2

Note the shared=true bit - it's needed, otherwise the command assumes you want to add the SR to the host.

Hope this helps.

**Comment by olivierlambert** [comment] 2018-11-10 07:46
@slamj1 Adding a iSCSI SR also works with XOA Free, no need to install it from the sources ;) But thank you for adding a guide with `xe` CLI, that's indeed another alternative :+1:

**Comment by slamj1** [comment] 2018-11-10 12:14
Thanks @olivierlambert, I wasn't aware of that. I'll add that to the toolbox :)

**Comment by BTLOPER** [comment] 2018-12-03 20:17
I was able to add a HBA SR via the console with no problem.  I imagine it would work for iSCSI as well.

**Comment by CAPS3** [comment] 2018-12-15 10:05
I was also running into the exact same issue as sammcj . The 'hotfix' build provided by Borzel in the link above provided by stormi resolved the issue for me. 

@olivierlambert There doesn't appear to be a gui option for iSCSI in XOA (sources), only Local, SMB or NFS - or was the implication to make use of the CLI from within XOA to mount the iSCSI SR successfully? (Or locally mounted iSCSI ?)

On a semi-related note re: trying to find the latest release of XCP-ng Center, I've found it's very easy to locate the XCP-ng Server ISO download links, but near impossible to find a recent version of an 'official' XCP-ng Center download - I feel really silly 😵 - Can someone please provide an official link to the latest exe's/msi's?

**Comment by borzel** [comment] 2018-12-15 10:18
Here you go: https://github.com/xcp-ng/xenadmin/releases

**Comment by olivierlambert** [comment] 2018-12-15 12:06
@CAPS3 I don't understand. What's missing in XO? You can create an iSCSI SR, be sure your XO is up to date please.

**Comment by CAPS3** [comment] 2018-12-18 09:16
Thanks once again borzel 👍 

@olivierlambert I apologise for the delay in getting back to you and elaborating. I'm currently running xo-server 5.31.1 and xo-web 5.31.0.
WEBUI -->Settings-->Remotes, & looking under "New File System Remote", I only have 3 options: Local, SMB and NFS -- no iSCSI (I feel silly again 😵); however, if I configure an iSCSI SR in XCP-ng Center, I -am- able to see the option listed under Backup NG (but only under Disaster recovery and Continuous Replication).

**Comment by olivierlambert** [comment] 2018-12-18 09:37
That's because there is a confusion.

1. If you want to add a Storage repository (where running VM disk are stored), it's in New/Storage.
2. A **remote** is a place to store backup, and we don't do that on iSCSI target.

**Comment by CAPS3** [comment] 2018-12-18 10:46
You're an absolute legend 😁 
Thanks for the clarification and quick response - I apologise for the confusion on my part.
