### ISSUE TITLE
Unable to install XCP-NG

### ISSUE THREAD

**Issue by juspitt** [xcp-ng/xcp#21] opened 2018-04-05 21:29 UTC
Hi i tried installing and it has been stuck on the "Preparing for installation..." screen on 45% for 25 minutes now i tried reboot and using a different hardrive still same results. am i doing something wrong?

![eeed5f0d054ed54d8099a367c498e9470199f6c59975106f62e30ba2ce751989](https://user-images.githubusercontent.com/38116729/38392815-d87e2ee8-38f6-11e8-9d98-7b0ab80a8f96.jpg)

**Comment by oallart** [comment] 2018-04-06 00:50
Ctrl+alt+f1 or f2,3 etc should show you some more verbose activity possibly

**Comment by olivierlambert** [comment] 2018-04-06 08:02
:+1: This is probably not related to XCP-ng specifically, probably something behind blocking.

**Comment by juspitt** [comment] 2018-04-07 01:32
what do you mean by "blocking"?

**Comment by olivierlambert** [comment] 2018-04-07 02:07
Corrupted ISO, I/O hanged on disk etc. Please check the output in other consoles (Ctrl Alt F3)

**Comment by borzel** [comment] 2018-07-08 23:30
I had the same issues with corrupted iso's. Just download a fresh one :-)

**Comment by gtvmsilva** [comment] 2018-08-29 02:04
I'm having the same issue. I've downloaded the ISO twice and checked the sha, everything looks fine in both ISOs. I'll try the 3rd ISO and different hardware too, but if some knows what the problem is I really appreciate the insight. I really want to be able to install XCP in my Mac Pro, I'm able to install Proxmox on it without issue, but want to start working more with XCP "Xen" since I use it a lot at work

**Comment by olivierlambert** [comment] 2018-08-29 09:19
Can you try with HTTP install? (using `https://xcp-ng.org/install` URL). However, IIRC, this step is doing disk formatting and partitioning, not yet installing RPMs…

**Comment by stormi** [comment] 2018-09-21 16:58
@juspitt @gtvmsilva Have you solved your installation issue?

**Comment by prods** [comment] 2019-01-25 21:03
I ran into the same issue earlier today when installing it on one of my Mac mini 2012 servers, it was stuck at 50%. I resolved it by booting into a live Ubuntu USB drive, running Gparted and removing all LMV and Physical partitions on the target SSDs. I did make sure all drives had a valid partition table since the drive where I was trying to install XCP-NG had it corrupted (not sure if it was related to the 50% installation issue). Created a GPT partition on the drive and after that it installed successfully. Hope it helps.

**Comment by stormi** [comment] 2020-11-30 14:37
In order to possibly work on this issue, we'd need tests with latest XCP-ng installer (8.2 currently) and error logs extracted from /tmp/install-log when the installation process hangs.

I'm closing this issue as "old". To anyone: feel free to open a new one if you have installation issues.

**Closed by stormi** 2020-11-30 14:37 UTC

**Comment by Bibi40k** [comment] 2021-11-09 22:12
Just reset NVRAMP, cmd+option+p+r

**Comment by Rexo81** [comment] 2022-07-22 01:58
I have a mac pro and I also have the same issue Mac pro 6.1 
febmem failed error

**Comment by Rexo81** [comment] 2022-07-22 01:58
Can anybody help me ?

**Comment by olivierlambert** [comment] 2022-07-22 11:02
You should probably ask on our community forum if there's other users installing XCP-ng on a Mac Pro :)
