### ISSUE TITLE
Software RAID install fails (7.6.) - many existing errors in disk layout

### ISSUE THREAD

**Issue by msgerbs** [xcp-ng/xcp#208] opened 2019-06-26 00:27 UTC
I am trying to do a Software RAID install of 7.6.0 on 2 128GB SATA SSDs connected to an LSI SAS9220-8i in JBOD mode, and when I select the drives it just goes right back to the select installation device screen. I also saw the same behavior using my server's built-in HP SAS controller. I don't know how to get the proper logs for this but if somebody can point me in the right direction I am happy to grab them.

For what it's worth I tried the 7.5.0 installer and had the same issue.

**Comment by stormi** [comment] 2019-06-26 09:29
Hi. You can switch to logs view or to a console with ALT + right arrow during the installation.

**Comment by stormi** [comment] 2019-06-26 09:30
You may also want to try XCP-ng 8.0 beta to check if the problem is still present.

**Comment by msgerbs** [comment] 2019-06-27 00:33
I tried XCP-ng 8.0 a few days ago and ran into the same issue.

After removing all other drives and attempting the install again I was able to do so without issues. I had previously put 4 of the drives in an mdadm array and I've seen some other issues posted about this causing problems, I wonder if that's what happened here?

I will try to reproduce and grab logs for you.

**Comment by msgerbs** [comment] 2019-06-27 01:09
Sorry, but what commands do I actually need to run to get the relevant logs here? I can see the logs on screen and I can get to a terminal, but I'm not quite sure where to go from there. I checked every file and folder in /var/log but don't see anything that resembles the output I see during the install, and the logs during the disk partitioning go by too fast to see what the issue is.

Right now I am at the "select device" screen immediately after a failed attempt to install to software RAID.

**Comment by nagilum99** [comment] 2019-06-27 01:21
I installed XCP-ng 7.6 with software RAID (mirror via setup) and upgraded later with 8 - it worked without any problems. Controller was an AMD A320 chipset S-ATA controller.

Under most distros you find helpful infos under /var/log/messages or /var/log/syslog
But I'm not sure about the install media from XCP-ng.

**Comment by msgerbs** [comment] 2019-06-27 01:36
Unfortunately /var/log/messages only has the startup message from rsyslogd.

**Comment by stormi** [comment] 2019-06-27 09:13
During installation the logs are in `/tmp/install-log`. After installation, they are in `/var/log/installer`.

**Comment by msgerbs** [comment] 2019-06-28 01:06
Here is the log: https://pastebin.com/RAcZ58Di

**Comment by stormi** [comment] 2019-11-25 10:36
Sorry, I overlooked your answer. Looking at the logs, I see lots of complaints from partitioning tools regarding the existing disk layout:

```
Caution! After loading partitions, the CRC doesn't check out!
****************************************************************************
Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
verification and recovery are STRONGLY recommended.
****************************************************************************
Warning! Main partition table overlaps the first partition by 33 blocks!
You will need to delete this partition or resize it in another utility.
 
Warning! Secondary partition table overlaps the last partition by
18446744071756026481 blocks!
You will need to delete this partition or resize it in another utility.
 
STANDARD ERROR:
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.
 
Warning! Main and backup partition tables differ! Use the 'c' and 'e' options
on the recovery & transformation menu to examine the two tables.
 
Warning! One or more CRCs don't match. You should repair the disk!
```

I think our installer is not robust enough to cope with all those errors and give your a proper error message in the UI.

**Comment by rjt** [comment] 2019-11-25 15:13
I have not read all the logs because I am on my phone, but have seen this
enough before that you want to completely delete the disks before install
as well as get SMART harddisk results from extended tests :

$ sudo su -

# echo For each drive X in your system, delete everything.  This can take a
long time:

# dd if=/dev/zero of=/dev/sdX bs=1G  &  pid=$!
# kill -s USR1 $pid

Probably want the gparted livecd or SysRescCD
GPartEd manages partitions
Gnome SMART gui tool runs tests and provides results.

https://gparted.org/livecd.php
http://www.system-rescue-cd.org/


My hunch is that the installer detects a previous install and tries to
rebuild an array instead of wiping everything clean. For instsnce,  the
installer is trying to rescue or upgrade a Citrix installation, it would
want to try to recover stuff first.

**Comment by stormi** [comment] 2019-11-25 15:34
Thanks for the input. I think this issue is converging towards #107

**Comment by stormi** [comment] 2021-01-19 18:15
Closing as duplicate for #107

**Closed by stormi** 2021-01-19 18:15 UTC
Labels: enhancement :new:, installer
