### ISSUE TITLE
IP not removed from previous interface when management interface is changed

### ISSUE THREAD

**Issue by kj4tbt-upenn** [xcp-ng/xcp#603] opened 2023-04-18 14:15 UTC
If you reconfigure the management interface to be on a different NIC using the TUI ("Configure Management Interface"), the IP address does not get removed from the old interface and will come back even after a reboot, which means the management network is then broken due to IP conflicts.  I had to use `xe pif-reconfigure-ip uuid=<uuid> mode=none` manually to remove it.  Reconfiguring the interface should remove the address from the previous interface.

**Comment by benjamreis** [comment] 2023-04-18 15:53
Duplicate of https://github.com/xapi-project/xsconsole/issues/8

**Closed by benjamreis** 2023-04-18 15:53 UTC
